---
title: "Advanced Regression for Emissions Predictions"
author: "Saloni Shah"
date: "11/06/2020"
output: html_document
---
#SETUP
```{r Load packages}
library(zoo)
library(sandwich)
library(plm)
library(lmtest)
library(jtools) 
library(ggstance)
library(tidyverse)
library(janitor)
library(naniar)
library(reshape)
library(wesanderson)
```

```{r Read in Data}
#pesticide use
pest_use <- read_csv("raw_data/faostat/pest_use.csv") %>% select(Country = Area, Year, pest_use = Value)
#units: tonnes use in country inc. all herbicides, insecticide, fungicide etc. timeframe: 1990-2020

#on-farm energy use emissions - converting to CO2e and subtracting fisheries energy emissions from total on-farm energy emissions
energy_emiss <- read_csv("raw_data/faostat/energy_use_emissions.csv") %>% 
  pivot_wider(names_from = Element, values_from = Value) %>% 
  mutate(tot_co2e = (`Emissions (CH4)`*28) + (`Emissions (N2O)`*265) + `Emissions (CO2)`) %>%  #multiply by AR5 GWP values FAO uses
  select(Country = Area, Year, tot_co2e, Item) %>% distinct() %>%  #remove duplicates of Bhutan, Hong Kong and several other countries 
  pivot_wider(names_from = Item, values_from = tot_co2e) %>% 
  mutate(en_emiss = `Total Energy` -coalesce(`Energy used in fishery`,0)) %>%  #calculate farm emissions as total - fishery 
  mutate(en_emiss = ifelse(en_emiss<0,NA,en_emiss)) %>%  #replace negative values w/ NA
  select(Country, Year, en_emiss)
#units: kilotonnes (i.e. gigagram) CO2e.  timeframe: 1970-2020

#fertilizer application emissions
fert_emiss <- read_csv("raw_data/faostat/fert_use_emissions.csv") %>% select(Country = Area, Year, fert_emiss = Value)
#units: kilotonnes (i.e. gigagram) CO2e, using AR5 GWP. timeframe: 1961-2020

#synthetic fertilizer use and use per ha cropland
fert_use_per_ha <- read_csv("raw_data/faostat/fert_use_per_ha_cropland.csv") %>% select(Country = Area, Year, fert_use_ha = Value)
#N use per ha of cropland. units: kg nutrient N/ha timeframe: 1961-2020

fert_use <- read_csv("raw_data/faostat/fert_use.csv") %>% select(Country = Area, Year, fert_use = Value) %>% mutate(fert_use= fert_use*1000)
#N agricultural use. units: convert from original units of tonnes N to kg N. timeframe: 1961-2020

#Yield and Cropland Data from calculate_calories_per_cropland.Rmd
prod <- read_csv("int_data/prod.cropland.csv")
```

```{r Calculate total fuel emissions, calculate emissions per ha for each input }
#join datasets
reg <- full_join(energy_emiss, fert_emiss) %>% full_join(fert_use) %>% full_join(fert_use_per_ha) %>% full_join(pest_use) %>% full_join(prod, by =  c("Country" = "country", "Year" = "year"))

#Fill in missing data for each column by country. Apply the last one carried forward method to each column in the dataframe (called reg below), grouping by country so that if the first observation is NA, the function doesn't replace with observation from different country. Will not fill in data for previous years.
reg <- reg %>% group_by(Country) %>% arrange(Country, Year) %>% fill(en_emiss:cropland)

#Calculate each emissions or input use per ha 
reg$en_emiss_ha <-reg$en_emiss/reg$cropland #units are gigagrams/ha
reg$p_ha <- reg$pest_use/reg$cropland #units are tons applied/ha
reg$fert_emiss_ha <- reg$fert_emiss/reg$cropland#units are gigagrams/ha

#reg calc yield
reg$yield <-  reg$tot_kcal/reg$cropland
plot(reg$yield, reg$fert_emiss_ha, main = "Yield vs. Syn N emissions per ha")
plot(reg$yield, reg$fert_use_ha, main = "Yield vs. Syn N use per ha")
plot(reg$yield, reg$en_emiss_ha, main = "Yield vs. On farm fuel emissions per ha")
plot(reg$yield, reg$p_ha, main = "Yield vs. Pesticides use per ha")
```

```{r Clean Data }
reg <-  clean_names(reg)  #makes all names lower case

#Determine if all yield values are non-zero
sum(reg$tot_kcal ==  0, na.rm=T) #none zero
sum(reg$cropland ==  0, na.rm=T) #none zero

#check for duplicate rows
get_dupes(reg, country, year) # no duplicates found

#count fuel emissions per ha, pesticide, and synthetic N observations by country
reg %>% group_by(country) %>% summarize(count = sum(is.na(en_emiss_ha)==FALSE)) 
reg %>% group_by(country) %>% summarize(count = sum(is.na(p_ha)==FALSE))
reg %>% group_by(country) %>% summarize(count = sum(is.na(fert_emiss_ha)==FALSE))
#results indicate different number of obs per country, an unbalanced panel dataset

#Convert 0's to NA's  - Not likely that a country has 0 fertilizer or fuel use if production and cropland  values are all non-zero. Likely that the "0" is missing data. These false 0's might influence regression estimates. All 0's will be converted to NAs and the regression will automatically eliminate all NAs. 
reg <- naniar::replace_with_na_all(data = reg, condition = ~.x == 0)

#Graph data to inspect for outliers
boxplot(reg$fert_use_ha)
boxplot(reg$p_ha) #visual representation of data points and outliers. #values are generally within 0.137 tons P/ha maximum (from World Bank) ; 5698 values are NA
plot(reg$yield, reg$en_emiss_ha) #there are some values for which yields are 0 but fuel emissions per ha is above 0.010 Gg/ha, values that are higher than 0.015 Gg/ha are all from Singapore, everything else is lower than 0.010
boxplot(reg$en_emiss_ha) #429 outliers

plot(reg$production_kcal/reg$cropland_ha, reg$fert_emiss_ha) #some high values have nearly 0 yields,  2012 values are NA, values are lower in magnitude 
boxplot(reg$fert_emiss_ha)
ggplot(reg) + geom_density(aes(fert_emiss_ha))

#remove countries with many substantial and unexplainable outlier values
outlier_en_countries <- reg %>% filter(en_emiss_ha>=0.15) %>% distinct(country) %>% pull() 
outlier_p_countries <- reg %>% filter(p_ha>=0.1) %>% distinct(country) %>% pull() 
reg <- reg %>% filter(!country %in% c(outlier_en_countries, outlier_p_countries))

reg
write_csv(reg, "int_data/reg.csv")
```

```{r Aggregate African countries data by region} 

#Subset by regions
#Member countries within each region are from the UN Statistics division : https://unstats.un.org/unsd/methodology/m49/overview/
country_groupings <- readxl::read_excel("raw_data/UNSD — Methodology.xlsx")

Africa <- country_groupings %>% filter(`Region Name`=="Africa") %>% select(`Country or Area`) %>% arrange(`Country or Area`) %>% pull()
W_Afr <- country_groupings %>% filter(`Intermediate Region Name`=="Western Africa") %>% select(`Country or Area`) %>% arrange(`Country or Area`) %>% pull()
E_Afr <- country_groupings %>% filter(`Intermediate Region Name`=="Eastern Africa") %>% select(`Country or Area`) %>% arrange(`Country or Area`) %>% pull()
C_Afr <- country_groupings %>% filter(`Intermediate Region Name`=="Middle Africa") %>% select(`Country or Area`) %>% arrange(`Country or Area`) %>% pull()
S_Afr <- country_groupings %>% filter(`Intermediate Region Name`=="Southern Africa") %>% select(`Country or Area`) %>% arrange(`Country or Area`) %>% pull()
N_Afr <- country_groupings %>% filter(`Sub-region Name`=="Northern Africa") %>% select(`Country or Area`) %>% arrange(`Country or Area`) %>% pull()

#define countries in Africa without matching names in faostat data in order to make names consistent for joining
Africa[which(!Africa %in% unique(reg$country))]

#match all possible, based on manual examination of faostat countries.  non-matching ones aren't listed separately in faostat
reg$country <- recode(reg$country, "Côte d'Ivoire"="Côte d’Ivoire")

#create new coumn with names as factors to revise
reg <- mutate(reg, Country_rename = country)

# add region name for countries in african regions AND in list of africa countries included in FOFA. this ensures that later regressions are conducted such that the fixed effect for a region only includes countries that are in the region for which predictions are being made (i.e. FOFA projections for northern africa exclude libya)
 reg$Country_rename[reg$Country_rename %in% E_Afr & reg$country %in% africa_scenario_countries] <-  "E_Afr"
 reg$Country_rename[reg$Country_rename %in% W_Afr & reg$country %in% africa_scenario_countries] <-  "W_Afr"
 reg$Country_rename[reg$Country_rename %in% C_Afr & reg$country %in% africa_scenario_countries] <-  "C_Afr"
 reg$Country_rename[reg$Country_rename %in% S_Afr & reg$country %in% africa_scenario_countries] <-  "S_Afr"
 reg$Country_rename[reg$Country_rename %in% N_Afr & reg$country %in% africa_scenario_countries] <-  "N_Afr"
 
# #filter data by region
 reg_E <- dplyr::filter(reg,reg$Country_rename == "E_Afr" )
 reg_W <- dplyr::filter(reg,reg$Country_rename == "W_Afr" )
 reg_C <- dplyr::filter(reg,reg$Country_rename == "C_Afr" )
 reg_S <- dplyr::filter(reg,reg$Country_rename == "S_Afr" )
 reg_N <- dplyr::filter(reg,reg$Country_rename == "N_Afr" )
```

```{r Not necessary to run - amount of missing data}

 #Amount of missing data for E.Afica region
# nrow(reg_E[reg_E$fert_emiss_ha == "NA",])/nrow(reg_E) * 100 #1.5% are NAs
# nrow(reg_E[reg_E$fert_use_ha == "NA",])/nrow(reg_E) * 100 #1.5% are NAs
# nrow(reg_E[reg_E$p_ha == "NA",])/nrow(reg_E) * 100 #54% of data are NAs
# nrow(reg_E[reg_E$en_emiss_ha == "NA",])/nrow(reg_E) * 100 #67% are NAs
# 
# #Amount of missing data for W.Afica region
# nrow(reg_W[reg_W$fert_emiss_ha == "NA",])/nrow(reg_W) * 100 #4% are NAs
# nrow(reg_W[reg_W$fert_use_ha == "NA",])/nrow(reg_W) * 100 #4% are NAs
# nrow(reg_W[reg_W$p_ha == "NA",])/nrow(reg_W) * 100 #65% of data are NAs
# nrow(reg_W[reg_W$en_emiss_ha == "NA",])/nrow(reg_W) * 100 #75% are NAs
# 
# #Amount of missing data for C.Afica region
# nrow(reg_C[reg_C$fert_emiss_ha == "NA",])/nrow(reg_C) * 100 #6% are NAs
# nrow(reg_C[reg_C$fert_use_ha == "NA",])/nrow(reg_C) * 100 #6% are NAs
# nrow(reg_C[reg_C$p_ha == "NA",])/nrow(reg_C) * 100 #65% of data are NAs
# nrow(reg_C[reg_C$en_emiss_ha == "NA",])/nrow(reg_C) * 100 #86% data missing
# 
# #Amount of missing data for S.Afica region
# nrow(reg_S[reg_S$fert_emiss_ha == "NA",])/nrow(reg_S) * 100 #8% are NAs
# nrow(reg_S[reg_S$fert_use_ha == "NA",])/nrow(reg_S) * 100 #8% are NAs
# nrow(reg_S[reg_S$p_ha == "NA",])/nrow(reg_S) * 100 #54% of data are NAs
# nrow(reg_S[reg_S$en_emiss_ha == "NA",])/nrow(reg_S) * 100  #62%
# 
# #Amount of missing data for N.Afica region
# nrow(reg_N[reg_N$fert_emiss_ha == "NA",])/nrow(reg_N) * 100 #5% are NAs
# nrow(reg_N[reg_N$fert_use_ha == "NA",])/nrow(reg_N) * 100 #5% are NAs
# nrow(reg_N[reg_N$p_ha == "NA",])/nrow(reg_N) * 100 #54% of data are NAs
# nrow(reg_N[reg_N$en_emiss_ha == "NA",])/nrow(reg_N) * 100  #35%
```

```{r Aggregate data for each region}

aggregate_reg <- function(region_data, region_name){
  output <- region_data %>% select(year,cropland, tot_kcal, en_emiss, fert_use, pest_use, fert_emiss) %>% 
  group_by(year) %>%
  summarise_all(sum, na.rm= TRUE) #sum total values across region by year
  
  #calculate per hectare values
  output <- output %>% mutate(yield = tot_kcal/cropland, en_emiss_ha = en_emiss/cropland, p_ha = pest_use/cropland, fert_emiss_ha = fert_emiss/cropland, fert_use_ha = fert_use/cropland, country = region_name)
  
  return(output)
}

reg_E_aggregate <- aggregate_reg(reg_E, "East")
reg_W_aggregate <- aggregate_reg(reg_E, "West")
reg_S_aggregate <- aggregate_reg(reg_E, "South")
reg_N_aggregate <- aggregate_reg(reg_E, "North")
reg_C_aggregate <- aggregate_reg(reg_E, "Central")
```

```{r Load in other countries' data and join it with African regions data}
#Filter out Africa data, keep non-Africa data 
reg_other_country <- reg %>% filter(!Country_rename %in% c("N_Afr", "C_Afr", "S_Afr","E_Afr","W_Afr")) %>% select(-Country_rename)

#Join Africa data with all of the countries' (non Africa) data
reg_other_country <- bind_rows(reg_other_country, reg_C_aggregate, reg_E_aggregate, reg_S_aggregate, reg_W_aggregate, reg_N_aggregate)
```

#Regression Code
```{r Run OLS linear regressions with filtered regression data to estimate relationship between yield and input use factor }

#OLS model includes country fixed effect to reduce bias

reg_all_countries <- naniar::replace_with_na_all(data = reg_all_countries, condition = ~.x == 0) #Make sure all 0's are converted to NAs, lm function automatically removes data with NAs 

#Outlier detection is based on yield values, could extend to the other inputs 
summary(reg_all_countries$yield) #Min.(20937), 1st Qu (3,022,995), Median (5,060,624), Mean (5,976,161), 3rd Qu. (7,910,443 ), Max.(34,303,176) 
boxplot(reg_all_countries$yield)
hist(reg_all_countries$yield,
  xlab = "yield",
  main = "Histogram of yield",
  breaks = sqrt(nrow(reg_all_countries))) # set number of bins
#Barbados, Kuwait, Belgium, Martinque occupy many of the highest values
#higher than 2*10^7 is an outlier based on historgram and barplot
sum(reg_all_countries$yield >= 20000000) #36 entries
sum(reg_all_countries$yield >= 20000000)/nrow(reg_all_countries) #~.5% of total entries
filter_reg <- filter(reg_all_countries, reg_all_countries$yield < 20000000)
#filter_reg_yrs <- filter(filter_reg, filter_reg$year > 1996) #sensitivity analysis - use last 20 years of data

#data on outliers for inputs
summary(reg_all_countries$synthetic_nitrogen_fertilizers)
boxplot(reg_all_countries$synthetic_nitrogen_fertilizers)
hist(reg_all_countries$synthetic_nitrogen_fertilizers,
  xlab = "fuel",
  main = "Histogram of fuel",
  breaks = sqrt(nrow(reg_all_countries)))

summary(reg_all_countries$fert_use)
boxplot(reg_all_countries$fert_use)
hist(reg_all_countries$fert_use,
  xlab = "fert_use",
  main = "Histogram of fuel",
  breaks = sqrt(nrow(reg_all_countries)))

boxplot(reg_all_countries$pesticides_total)
hist(reg_all_countries$pesticides_total,
  xlab = "pesticides",
  main = "Histogram of fuel",
  breaks = sqrt(nrow(reg_all_countries)))

summary(reg_all_countries$fuel_emissions)
hist(reg_all_countries$fuel_emissions,
  xlab = "fuel",
  main = "Histogram of fuel",
  breaks = sqrt(nrow(reg_all_countries)))

#Sensitivity - calculate global values for each column in filter_reg
#temp <- filter_reg
#temp[is.na(temp)] <- 0
#world_reg <- temp %>% group_by(year) %>% summarise(across(-country, sum))
#world_reg$yield <- world_reg$production_kcal/world_reg$cropland_ha
#world_reg$en_emiss_ha <- world_reg$fuel_emissions/world_reg$cropland_ha
#world_reg$p_ha <- world_reg$pesticides_total/world_reg$cropland_ha
#world_reg$fert_emiss_ha <- world_reg$synthetic_nitrogen_fertilizers/world_reg$cropland_ha
#world_reg$fert_use_ha <- world_reg$fert_use/world_reg$cropland_ha
#world_reg$country <- "World"
#world_reg[world_reg == 0] <- NA
#filter_reg_2 <- full_join(filter_reg, world_reg)

#Sensitivity , increase fertilizer data by 3X
# filter_reg$synthetic_nitrogen_fertilizers <- filter_reg$synthetic_nitrogen_fertilizers  * 3
# filter_reg$fert_use <- filter_reg$fert_use * 3
# filter_reg$fert_emiss_ha <- filter_reg$synthetic_nitrogen_fertilizers/filter_reg$cropland_ha
# filter_reg$fert_use_ha <- filter_reg$fert_use/filter_reg$cropland_ha

#Pesticides Use OLS regression
p.ols <- lm(filter_reg, formula = log(p_ha) ~ log(yield) + factor(country))
#p.ols <- lm(filter_reg_2, formula = log(p_ha) ~ log(yield) + factor(country)) #Global yield sensitivity 
#p.ols <- lm(filter_reg_yrs , formula = log(p_ha) ~ log(yield) + factor(country)) #last 20 years sensitivity


#Fuel Emissions OLS Regression
filter_f_reg <- filter(filter_reg, filter_reg$en_emiss_ha > 0)
fuel.ols <- lm(filter_f_reg , formula = log(en_emiss_ha) ~ log(yield) + factor(country))
#filter_f_reg_2 <- filter(filter_reg_2, filter_reg_2$en_emiss_ha > 0)
#fuel.ols <- lm(filter_f_reg_2 , formula = log(en_emiss_ha) ~ log(yield) + factor(country)) #Global yield sensitivity 
#fuel.ols <- lm(filter_f_reg_2 , formula = log(en_emiss_ha) ~ log(yield) + factor(country))

#filter_f_reg_yrs <- filter(filter_reg_yrs, filter_reg_yrs$en_emiss_ha > 0)
#fuel.ols <- lm(filter_f_reg_yrs , formula = log(en_emiss_ha) ~ log(yield) + factor(country)) #Global yield sensitivity 


#Synthetic N emissions OLS Regression 
filter_syn_reg <- filter(filter_reg, filter_reg$fert_emiss_ha > 0)
syn_n.ols <- lm(filter_syn_reg, formula = log(fert_emiss_ha) ~ log(yield) + factor(country)) #no #outliers in boxplot

#filter_syn_reg_yrs <- filter(filter_reg_yrs, filter_reg_yrs$fert_emiss_ha > 0)
#syn_n.ols <- lm(filter_syn_reg_yrs, formula = log(fert_emiss_ha) ~ log(yield) + factor(country))

#Global yield sensitivity 
#filter_syn_reg_2 <- filter(filter_reg_2, filter_reg_2$fert_emiss_ha > 0)
#syn_n.ols <- lm(filter_syn_reg_2, formula = log(fert_emiss_ha) ~ log(yield) + factor(country))

#Synthetic N use or application OLS regression
filter_fert_use_reg <- filter(filter_reg, filter_reg$fert_use_ha > 0)
fert_use.ols <- lm(filter_fert_use_reg, formula = log(fert_use_ha) ~ log(yield) + factor(country))

#filter_fert_use_reg_yrs <- filter(filter_reg_yrs, filter_reg_yrs$fert_use_ha > 0)
#fert_use.ols <- lm(filter_fert_use_reg_yrs, formula = log(fert_use_ha) ~ log(yield) + factor(country))
#Global yield sensitivity 
#filter_fert_use_reg_2 <- filter(filter_reg_2, filter_reg_2$fert_use_ha > 0)
#fert_use.ols <- lm(filter_fert_use_reg_2, formula = log(fert_use_ha) ~ log(yield) + factor(country))

```

```{r Import yields for each scenario and region to estumate input use and emissions}

scenarios <- read_csv("int_data/scenarios.csv") #yields are in kcal/ha
#Convert country names in scenarios to East, West, Central, South, North
scenarios$region <- recode(scenarios$region, E_Afr = "East", C_Afr = "Central", S_Afr = "South", N_Afr = "North", W_Afr = "West")
#scenarios$...1 <- NULL

b <- filter(scenarios, scenario == "b")
b_e <- b %>% filter(region=="East") %>% select(yield, country = region)
b_w <- b %>% filter(region=="West") %>% select(yield, country = region)
b_s <- b %>% filter(region=="South") %>% select(yield, country = region)
b_c <- b %>% filter(region=="Central") %>% select(yield, country = region)
b_n <- b %>% filter(region=="North") %>% select(yield, country = region)
b_a <- b %>% filter(region=="Africa") %>% select(yield, country = region)

p <- filter(scenarios, scenario == "p")
p_e <- p %>% filter(region=="East") %>% select(yield, country = region)
p_w <- p %>% filter(region=="West") %>% select(yield, country = region)
p_s <- p %>% filter(region=="South") %>% select(yield, country = region)
p_c <- p %>% filter(region=="Central") %>% select(yield, country = region)
p_n <- p %>% filter(region=="North") %>% select(yield, country = region)
p_a <- p %>% filter(region=="Africa") %>% select(yield, country = region)

h_alt <- filter(scenarios, scenario == "h")
h_alt_e <- h_alt %>% filter(region=="East") %>% select(yield, country = region)
h_alt_w <- h_alt %>% filter(region=="West") %>% select(yield, country = region)
h_alt_s <- h_alt %>% filter(region=="South") %>% select(yield, country = region)
h_alt_c <- h_alt %>% filter(region=="Central") %>% select(yield, country = region)
h_alt_n <- h_alt %>% filter(region=="North") %>% select(yield, country = region)
h_alt_a <- h_alt %>% filter(region=="Africa") %>% select(yield, country = region)

#Sensitivity: Pass global yield samples instead of regional African yield samples through OLS models
# regions_scenario_linus <- read_csv("~/Google Drive/My Drive/Food & Farming/Energy in #ag/LandDemand/regions_scenario_linus.csv") #yields are in kcal/ha
# b <- filter(regions_scenario_linus, scenario == "b") %>% select(yield)
# b$country <- "World"
# p <- filter(regions_scenario_linus, scenario == "p")  %>% select(yield)
# p$country <- "World"
# h_alt <- filter(regions_scenario_linus, scenario == "h")  %>% select(yield)
# h_alt$country <- "World"

```

```{r Sensitivity Analysis calculate Africa's emissions using global yield values}
#pest_b <- exp(predict(p.ols, newdata  = b, interval = "confidence", level = 0.95))
 #pest_p <- exp(predict(p.ols, newdata  = p, interval = "confidence", level = 0.95))
 #pest_h <- exp(predict(p.ols, newdata  = h_alt, interval = "confidence", level = 0.95))
# 
# fuel_b <- exp(predict(fuel.ols, newdata  = b, interval = "confidence", level = 0.95))
# fuel_p <- exp(predict(fuel.ols, newdata  = p, interval = "confidence", level = 0.95))
# fuel_h <- exp(predict(fuel.ols, newdata  = h_alt, interval = "confidence", level = 0.95))
# 
# synN_b <- exp(predict(syn_n.ols, newdata  = b, interval = "confidence", level = 0.95))
# synN_p <- exp(predict(syn_n.ols, newdata  = p, interval = "confidence", level = 0.95))
# synN_h <- exp(predict(syn_n.ols, newdata  = h_alt, interval = "confidence", level = 0.95))
# 
# synNuse_b <- exp(predict(fert_use.ols, newdata  = b, interval = "confidence", level = 0.95))
# synNuse_p <- exp(predict(fert_use.ols, newdata  = p, interval = "confidence", level = 0.95))
# synNuse_h <- exp(predict(fert_use.ols, newdata  = h_alt, interval = "confidence", level = 0.95))
# 
# #calculate input use and emissions for each scenario for the world
# area_b <- regions_scenario_linus %>% dplyr::select(harv_area, scenario) %>% filter(scenario == "b")
# area_p <- regions_scenario_linus %>% dplyr::select(harv_area, scenario) %>% filter( scenario == "p")
# area_h <- regions_scenario_linus %>% dplyr::select(harv_area, scenario) %>% filter( scenario == "h")
# 
# #Conversion factors for fertilizer and pesticides manufacturing emissions
#fert_ef <- 5.66 #5.66 kg CO2 eq/kg product  is the fertilizer EF
 #pest_ef <- 25.5 # 25.5 kg cO2e/kg applied is the pesticides EF
# kg_to_Gg <- (1/10^6)  #1 Gg/1 * 10^6 kg
#tons_to_Gg <- .001 #tons to Gg; formula with units : X tons applied *  Y tons CO2eq/tons product applied * .001 Gg/ ton. Y represents the pesticides emissions factor.
# 
# #Syn N manufacturing emissions (synthetic N Use is in kg per ha)
#synNuse_emis_b <- area_b$harv_area * synNuse_b[1] * fert_ef * kg_to_Gg
#synNuse_emis_p <- area_p$harv_area * synNuse_p[1] * fert_ef * kg_to_Gg
#synNuse_emis_h <- area_h$harv_area * synNuse_h[1] * fert_ef * kg_to_Gg
# 
# ##Fuel Emissions (Gg CO2e are original units, final results are also in Gg CO2e)
# f_emis_b <- area_b$harv_area * fuel_b[1]
# f_emis_p <- area_p$harv_area * fuel_p[1]
# f_emis_h <- area_h$harv_area * fuel_h[1]
# 
# #Pesticides manufacturing emissions (#Pesticides use is in tons per ha )
# p_emis_b <- area_b$harv_area * pest_b[1] * pest_ef  * tons_to_Gg # results in pesticides manufacturing emissions in Gg CO2e. "pest_b[1]" refers to the fitted pesticides emis/ha.
# p_emis_p <- area_p$harv_area * pest_p[1] * pest_ef  * tons_to_Gg
# p_emis_h <- area_h$harv_area * pest_h[1] * pest_ef  * tons_to_Gg
# 
# #Syn N emissions (Gg CO2e original units, final results are in Gg CO2e )
#synN_emis_b <- area_b$harv_area * synN_b[1] # results in syn nitrogen fertilizer emissions in Gg CO2e. "synNuse_b_e[1]" refers to the fitted synthetic n emis/ha.
# synN_emis_p <- area_p$harv_area * synN_p[1]
# synN_emis_h <- area_h$harv_area * synN_h[1]
```

```{r Predict pesticide use/ha for each region}

#Make predictions on pesticides use for each scenario for East Africa
pest_b_e <- exp(predict(p.ols, newdata  = b_e, interval = "confidence", level = 0.95))
pest_proj_e <- exp(predict(p.ols, newdata  = p_e,  interval = "confidence", level = 0.95))
pest_h_alt_e <- exp(predict(p.ols, newdata  = h_alt_e,  interval = "confidence", level = 0.95))

p_ha_E <- rbind(pest_b_e, pest_proj_e , pest_h_alt_e)
colnames(p_ha_E) <- c("fit_p_ha_e","lwr_p_ha_e", "upr_p_ha_e")

#Make predictions on pesticides use for each scenario for West Africa
pest_b_w <- exp(predict(p.ols, newdata  = b_w, interval = "confidence", level = 0.95))
pest_proj_w <- exp(predict(p.ols, newdata  = p_w,  interval = "confidence", level = 0.95))
pest_h_alt_w <- exp(predict(p.ols, newdata  = h_alt_w,  interval = "confidence", level = 0.95))

p_ha_W <- rbind(pest_b_w,pest_proj_w ,  pest_h_alt_w)
colnames(p_ha_W) <- c("fit_p_ha_w","lwr_p_ha_w", "upr_p_ha_w")

#Make predictions on pesticides use for each scenario for South Africa
pest_b_s <- exp(predict(p.ols, newdata  = b_s, interval = "confidence", level = 0.95))
pest_proj_s <- exp(predict(p.ols, newdata  = p_s,  interval = "confidence", level = 0.95))
pest_h_alt_s <- exp(predict(p.ols, newdata  = h_alt_s,  interval = "confidence", level = 0.95))

p_ha_S <- rbind(pest_b_s , pest_proj_s , pest_h_alt_s)
colnames(p_ha_S) <- c("fit_p_ha_s","lwr_p_ha_s", "upr_p_ha_s")

#Make predictions on pesticides use for each scenario for Central Africa
pest_b_c <- exp(predict(p.ols, newdata  = b_c, interval = "confidence", level = 0.95))
pest_proj_c <- exp(predict(p.ols, newdata  = p_c,  interval = "confidence", level = 0.95))
pest_h_alt_c <- exp(predict(p.ols, newdata  = h_alt_c,  interval = "confidence", level = 0.95))

p_ha_C <- rbind(pest_b_c , pest_proj_c , pest_h_alt_c)
colnames(p_ha_C) <- c("fit_p_ha_c","lwr_p_ha_c", "upr_p_ha_c")

#Make predictions on pesticides use for each scenario for North Africa
pest_b_n <- exp(predict(p.ols, newdata = b_n, interval = "confidence", level = 0.95))
pest_proj_n <- exp(predict(p.ols, newdata  = p_n,  interval = "confidence", level = 0.95))
pest_h_alt_n <- exp(predict(p.ols, newdata  = h_alt_n,  interval = "confidence", level = 0.95))

p_ha_N <- rbind(pest_b_n , pest_proj_n , pest_h_alt_n)
colnames(p_ha_N) <- c("fit_p_ha_n","lwr_p_ha_n", "upr_p_ha_n")

```

```{r Predict on-farm fuel emis/ha for each region}
#Make predictions on fuel emis for each scenario for East Africa
fuel_b_e <- exp(predict(fuel.ols, newdata  = b_e, interval = "confidence", level = 0.95))
fuel_proj_e <- exp(predict(fuel.ols, newdata  = p_e,  interval = "confidence", level = 0.95))
fuel_h_alt_e <- exp(predict(fuel.ols, newdata  = h_alt_e,  interval = "confidence", level = 0.95))

en_emiss_ha_E <- rbind(fuel_b_e, fuel_proj_e ,  fuel_h_alt_e)
colnames(en_emiss_ha_E) <- c("fit_en_emiss_ha_e","lwr_en_emiss_ha_e", "upr_en_emiss_ha_e")

#Make predictions on fuel emissions for each scenario for West Africa
fuel_b_w <- exp(predict(fuel.ols, newdata  = b_w, interval = "confidence", level = 0.95))
fuel_proj_w <- exp(predict(fuel.ols, newdata  = p_w,  interval = "confidence", level = 0.95))
fuel_h_alt_w <- exp(predict(fuel.ols, newdata  = h_alt_w,  interval = "confidence", level = 0.95))

en_emiss_ha_W <- rbind(fuel_b_w, fuel_proj_w , fuel_h_alt_w)
colnames(en_emiss_ha_W) <- c("fit_en_emiss_ha_w","lwr_en_emiss_ha_w", "upr_en_emiss_ha_w")

#Make predictions on fuel emissions for each scenario for South Africa
fuel_b_s <- exp(predict(fuel.ols, newdata  = b_s, interval = "confidence", level = 0.95))
fuel_proj_s <- exp(predict(fuel.ols, newdata  = p_s,  interval = "confidence", level = 0.95))
fuel_h_alt_s <- exp(predict(fuel.ols, newdata  = h_alt_s,  interval = "confidence", level = 0.95))

en_emiss_ha_S <- rbind(fuel_b_s  , fuel_proj_s ,  fuel_h_alt_s)
colnames(en_emiss_ha_S) <- c("fit - en_emiss_ha_s","lwr - en_emiss_ha_s", "upr)en_emiss_ha_s")

#Make predictions on fuel emissions for each scenario for Central Africa
fuel_b_c <- exp(predict(fuel.ols, newdata  = b_c, interval = "confidence", level = 0.95))
fuel_proj_c <- exp(predict(fuel.ols, newdata  = p_c,  interval = "confidence", level = 0.95))
fuel_h_alt_c <- exp(predict(fuel.ols, newdata  = h_alt_c,  interval = "confidence", level = 0.95))

en_emiss_ha_C <- rbind(fuel_b_c , fuel_proj_c ,  fuel_h_alt_c)
colnames(en_emiss_ha_C) <- c("fit_en_emiss_ha_c","lwr_en_emiss_ha_c", "upr_en_emiss_ha_c")

#Make predictions on fuel emissions for each scenario for North Africa
fuel_b_n <- exp(predict(fuel.ols, newdata = b_n, interval = "confidence", level = 0.95))
fuel_proj_n <- exp(predict(fuel.ols, newdata  = p_n,  interval = "confidence", level = 0.95))
fuel_h_alt_n <- exp(predict(fuel.ols, newdata  = h_alt_n,  interval = "confidence", level = 0.95))

en_emiss_ha_N <- rbind(fuel_b_n  , fuel_proj_n  , fuel_h_alt_n)
colnames(en_emiss_ha_N) <- c("fit_en_emiss_ha_n","lwr_en_emiss_ha_n", "upr_en_emiss_ha_n")

 #Save fuel emissions per ha as table for working paper
#en_emiss_ha_W <- as.data.frame(en_emiss_ha_W) 
#en_emiss_ha_W$Region <- "West Africa"
# en_emiss_ha_E <- as.data.frame(en_emiss_ha_E) 
# en_emiss_ha_E$Region <- "East Africa"
# en_emiss_ha_N <- as.data.frame(en_emiss_ha_N) 
#en_emiss_ha_N$Region <- "North Africa"
#en_emiss_ha_S <- as.data.frame(en_emiss_ha_S) 
# en_emiss_ha_S$Region <- "South Africa"
# en_emiss_ha_C <- as.data.frame(en_emiss_ha_C) 
# en_emiss_ha_C$Region <- "Central Africa"
# 
# en_emiss_ha_W$Scenario <- c("Baseline", "Projected","High")
# en_emiss_ha_S$Scenario <- c("Baseline", "Projected","High")
# en_emiss_ha_C$Scenario <- c("Baseline", "Projected","High")
#en_emiss_ha_N$Scenario <- c("Baseline", "Projected","High")
 #en_emiss_ha_E$Scenario <- c("Baseline", "Projected","High")
# 
 #colnames(en_emiss_ha_W) <- c("fit", "lwr", "upr", "Region", "Scenario")
 #colnames(en_emiss_ha_E) <- c("fit", "lwr", "upr", "Region", "Scenario")
# colnames(en_emiss_ha_S) <- c("fit", "lwr", "upr", "Region", "Scenario")
#colnames(en_emiss_ha_N) <- c("fit", "lwr", "upr", "Region", "Scenario")
#colnames(en_emiss_ha_C) <- c("fit", "lwr", "upr", "Region", "Scenario")
# 
 #en_emiss_ha_tbl <- rbind(en_emiss_ha_W,en_emiss_ha_S, en_emiss_ha_C, en_emiss_ha_N, en_emiss_ha_E )
#write.csv(en_emiss_ha_tbl,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/en_emiss_ha.csv")




```

```{r Make predictions on synthetic N emissions for each scenario}

#Make predictions on fuel use for each scenario for East Africa
synN_b_e <- exp(predict(syn_n.ols, newdata  = b_e, interval = "confidence", level = 0.95))
 synN_proj_e <- exp(predict(syn_n.ols, newdata  = p_e,  interval = "confidence", level = 0.95))
 synN_h_alt_e <- exp(predict(syn_n.ols, newdata  = h_alt_e,  interval = "confidence", level = 0.95))

#For sensitivity analysis, linear model
# synN_b_e <- predict(syn_n.ols, newdata  = b_e, interval = "confidence", level = 0.95)
# synN_proj_e <- predict(syn_n.ols, newdata  = p_e,  interval = "confidence", level = 0.95)
# synN_h_alt_e <- predict(syn_n.ols, newdata  = h_alt_e,  interval = "confidence", level = 0.95)

fert_emiss_ha_E <- rbind(synN_b_e, synN_proj_e ,  synN_h_alt_e)
colnames(fert_emiss_ha_E) <- c("fit_fert_emiss_ha_e","lwr_fert_emiss_ha_e", "upr_fert_emiss_ha_e")

#Make predictions on pesticides use for each scenario for West Africa
 synN_b_w <- exp(predict(syn_n.ols, newdata  = b_w, interval = "confidence", level = 0.95))
 synN_proj_w <- exp(predict(syn_n.ols, newdata  = p_w,  interval = "confidence", level = 0.95))
 synN_h_alt_w <- exp(predict(syn_n.ols, newdata  = h_alt_w,  interval = "confidence", level = 0.95))

#for sensitivity analysis, linear model
# synN_b_w <- predict(syn_n.ols, newdata  = b_w, interval = "confidence", level = 0.95)
# synN_proj_w <- predict(syn_n.ols, newdata  = p_w,  interval = "confidence", level = 0.95)
# synN_h_alt_w <- predict(syn_n.ols, newdata  = h_alt_w,  interval = "confidence", level = 0.95)

fert_emiss_ha_W <- rbind(synN_b_w, synN_proj_w ,  synN_h_alt_w)
colnames(fert_emiss_ha_W) <- c("fit_fert_emiss_ha_w","lwr_fert_emiss_ha_w", "upr_fert_emiss_ha_w")

#Make predictions on pesticides use for each scenario for South Africa
synN_b_s <- exp(predict(syn_n.ols, newdata  = b_s, interval = "confidence", level = 0.95)) 
synN_proj_s <- exp(predict(syn_n.ols, newdata  = p_s,  interval = "confidence", level = 0.95))
synN_h_alt_s <- exp(predict(syn_n.ols, newdata  = h_alt_s,  interval = "confidence", level = 0.95))

#For sensitivity analysis, linear model
# synN_b_s <- predict(syn_n.ols, newdata  = b_s, interval = "confidence", level = 0.95)
# synN_proj_s <- predict(syn_n.ols, newdata  = p_s,  interval = "confidence", level = 0.95)
# synN_h_alt_s <- predict(syn_n.ols, newdata  = h_alt_s,  interval = "confidence", level = 0.95)

fert_emiss_ha_S <- rbind(synN_b_s , synN_proj_s ,  synN_h_alt_s)
colnames(fert_emiss_ha_S) <- c("fit_fert_emiss_ha_s","lwr_fert_emiss_ha_s", "upr_fert_emiss_ha_s")

#Make predictions on pesticides use for each scenario for Central Africa
 synN_b_c <- exp(predict(syn_n.ols, newdata  = b_c, interval = "confidence", level = 0.95))
 synN_proj_c <- exp(predict(syn_n.ols, newdata  = p_c,  interval = "confidence", level = 0.95))
 synN_h_alt_c <- exp(predict(syn_n.ols, newdata  = h_alt_c,  interval = "confidence", level = 0.95))

#for sensitivity analysis, linear model
# synN_b_c <- predict(syn_n.ols, newdata  = b_c, interval = "confidence", level = 0.95)
# synN_proj_c <- predict(syn_n.ols, newdata  = p_c,  interval = "confidence", level = 0.95)
# synN_h_alt_c <- predict(syn_n.ols, newdata  = h_alt_c,  interval = "confidence", level = 0.95)

fert_emiss_ha_C <- rbind(synN_b_c , synN_proj_c , synN_h_alt_c)
colnames(fert_emiss_ha_C) <- c("fit_fert_emiss_ha_c","lwr_fert_emiss_ha_c", "upr_fert_emiss_ha_c")

#Make predictions on syn N emissions for each scenario for North Africa
 synN_b_n <- exp(predict(syn_n.ols, newdata = b_n, interval = "confidence", level = 0.95))
 synN_proj_n <- exp(predict(syn_n.ols, newdata  = p_n,  interval = "confidence", level = 0.95))
 synN_h_alt_n <- exp(predict(syn_n.ols, newdata  = h_alt_n,  interval = "confidence", level = 0.95))

#for sensitivity analysis, linear model
# synN_b_n <- predict(syn_n.ols, newdata = b_n, interval = "confidence", level = 0.95)
# synN_proj_n <- predict(syn_n.ols, newdata  = p_n,  interval = "confidence", level = 0.95)
# synN_h_alt_n <- predict(syn_n.ols, newdata  = h_alt_n,  interval = "confidence", level = 0.95)

fert_emiss_ha_N <- rbind(synN_b_n , synN_proj_n ,  synN_h_alt_n)
colnames(fert_emiss_ha_N) <- c("fit_fert_emiss_ha_n","lwr_fert_emiss_ha_n", "upr_fert_emiss_ha_n")

```

```{r}
#Make predictions on synthetic N use for each scenario for East Africa

synNuse_b_e <- exp(predict(fert_use.ols, newdata  = b_e, interval = "confidence", level = 0.95))
synNuse_proj_e <- exp(predict(fert_use.ols, newdata  = p_e,  interval = "confidence", level = 0.95))
synNuse_h_alt_e <- exp(predict(fert_use.ols, newdata  = h_alt_e,  interval = "confidence", level = 0.95))

# synNuse_b_e <- predict(fert_use.ols, newdata  = b_e, interval = "confidence", level = 0.95)
# synNuse_proj_e <- predict(fert_use.ols, newdata  = p_e,  interval = "confidence", level = 0.95)
# synNuse_h_alt_e <- predict(fert_use.ols, newdata  = h_alt_e,  interval = "confidence", level = 0.95)

synNuse_ha_E <- rbind(synNuse_b_e ,synNuse_proj_e ,synNuse_h_alt_e)
colnames(synNuse_ha_E) <- c("fit_synNuse_ha_e","lwr_synNuse_ha_e", "upr_synNuse_ha_e")

#Make predictions on synthetic N use for each scenario for West Africa
 synNuse_b_w <- exp(predict(fert_use.ols, newdata  = b_w, interval = "confidence", level = 0.95))
 synNuse_proj_w <- exp(predict(fert_use.ols, newdata  = p_w,  interval = "confidence", level = 0.95))
 synNuse_h_alt_w <- exp(predict(fert_use.ols, newdata  = h_alt_w,  interval = "confidence", level = 0.95))

# synNuse_b_w <- predict(fert_use.ols, newdata  = b_w, interval = "confidence", level = 0.95)
# synNuse_proj_w <- predict(fert_use.ols, newdata  = p_w,  interval = "confidence", level = 0.95)
# synNuse_h_alt_w <- predict(fert_use.ols, newdata  = h_alt_w,  interval = "confidence", level = 0.95)

synNuse_ha_W <- rbind(synNuse_b_w, synNuse_proj_w ,  synNuse_h_alt_w)
colnames(synNuse_ha_W) <- c("fit_synNuse_ha_w","lwr_synNuse_ha_w", "upr_synNuse_ha_w")


#Make predictions on synthetic N use use for each scenario for South Africa
synNuse_b_s <- exp(predict(fert_use.ols, newdata  = b_s, interval = "confidence", level = 0.95))
synNuse_proj_s <- exp(predict(fert_use.ols, newdata  = p_s,  interval = "confidence", level = 0.95))
synNuse_h_alt_s <- exp(predict(fert_use.ols, newdata  = h_alt_s,  interval = "confidence", level = 0.95))

#for senstiviity analysis, linear model
# synNuse_b_s <- predict(fert_use.ols, newdata  = b_s, interval = "confidence", level = 0.95)
# synNuse_proj_s <- predict(fert_use.ols, newdata  = p_s,  interval = "confidence", level = 0.95)
# synNuse_h_alt_s <- predict(fert_use.ols, newdata  = h_alt_s,  interval = "confidence", level = 0.95)

synNuse_ha_S <- rbind(synNuse_b_s , synNuse_proj_s ,  synNuse_h_alt_s)
colnames(synNuse_ha_S) <- c("fit_synNuse_ha_s","lwr_synNuse_ha_s", "upr_synNuse_ha_s")

#Make predictions on Synthetic N use use for each scenario for Central Africa
 synNuse_b_c <- exp(predict(fert_use.ols, newdata  = b_c, interval = "confidence", level = 0.95))
 synNuse_proj_c <- exp(predict(fert_use.ols, newdata  = p_c,  interval = "confidence", level = 0.95))
 synNuse_h_alt_c <- exp(predict(fert_use.ols, newdata  = h_alt_c,  interval = "confidence", level = 0.95))

#for senstiviity analysis, linear model
# synNuse_b_c <- predict(fert_use.ols, newdata  = b_c, interval = "confidence", level = 0.95)
# synNuse_proj_c <- predict(fert_use.ols, newdata  = p_c,  interval = "confidence", level = 0.95)
# synNuse_h_alt_c <- predict(fert_use.ols, newdata  = h_alt_c,  interval = "confidence", level = 0.95)

synNuse_ha_C <- rbind(synNuse_b_c  , synNuse_proj_c ,  synNuse_h_alt_c)
colnames(synNuse_ha_C) <- c("fit_synNuse_ha_c","lwr_synNuse_ha_c", "upr_synNuse_ha_c")

#Make predictions on synthetic N use for each scenario for North Africa
 synNuse_b_n <- exp(predict(fert_use.ols, newdata = b_n, interval = "confidence", level = 0.95))
synNuse_proj_n <- exp(predict(fert_use.ols, newdata  = p_n,  interval = "confidence", level = 0.95))
 synNuse_h_alt_n <- exp(predict(fert_use.ols, newdata  = h_alt_n,  interval = "confidence", level = 0.95))

#for senstiviity analysis, linear model
# synNuse_b_n <- predict(fert_use.ols, newdata = b_n, interval = "confidence", level = 0.95)
# synNuse_proj_n <- predict(fert_use.ols, newdata  = p_n,  interval = "confidence", level = 0.95)
# synNuse_h_alt_n <- predict(fert_use.ols, newdata  = h_alt_n,  interval = "confidence", level = 0.95)

synNuse_ha_N <- rbind(synNuse_b_n , synNuse_proj_n, synNuse_h_alt_n )
colnames(synNuse_ha_N) <- c("fit_synNuse_ha_n","lwr_synNuse_ha_n", "upr_synNuse_ha_n")

#Save Synthethic N application, Pesticides application rates for all regions and scenarios
synNapp_N <- as.data.frame(synNuse_ha_N)
synNapp_N$`lwr - synNuse_ha_n` <- NULL
synNapp_N$`upr - synNuse_ha_n` <- NULL
synNapp_N$Region <- "North"
synNapp_N$Scenario <- c("Baseline", "Projected", "High")
colnames(synNapp_N) <- c("synNuse", "Region", "Scenario")

synNapp_C <- as.data.frame(synNuse_ha_C)
synNapp_C$`lwr - synNuse_ha_c` <- NULL
synNapp_C$`upr - synNuse_ha_c` <- NULL
synNapp_C$Region <- "Central"
synNapp_C$Scenario <- c("Baseline", "Projected", "High")
colnames(synNapp_C) <- c("synNuse", "Region", "Scenario")

synNapp_S <- as.data.frame(synNuse_ha_S)
synNapp_S$`lwr - synNuse_ha_s` <- NULL
synNapp_S$`upr - synNuse_ha_s` <- NULL
synNapp_S$Region <- "Southern"
synNapp_S$Scenario <- c("Baseline", "Projected", "High")
colnames(synNapp_S) <- c("synNuse" ,"Region", "Scenario")

synNapp_E <- as.data.frame(synNuse_ha_E)
synNapp_E$`lwr - syn_Nuse_ha_e`<- NULL
synNapp_E$`upr - syn_Nuse_ha_e` <- NULL
synNapp_E$Region <- "East"
synNapp_E$Scenario <- c("Baseline", "Projected", "High")
colnames(synNapp_E) <- c("synNuse" ,"Region", "Scenario")

synNapp_W <- as.data.frame(synNuse_ha_W)
synNapp_W$`lwr - syn_Nuse_ha_w` <- NULL
synNapp_W$`upr - syn_Nuse_ha_w` <- NULL
synNapp_W$Region <- "West"
synNapp_W$Scenario <- c("Baseline", "Projected", "High")
colnames(synNapp_W) <- c("synNuse", "Region", "Scenario")

synNapp <- rbind(synNapp_C, synNapp_E, synNapp_N, synNapp_S, synNapp_W)
rownames(synNapp) <- NULL

#Repeat for pesticides use
p_app_N <- as.data.frame(p_ha_N)
p_app_N$`lwr - p_ha_N` <- NULL
p_app_N$`upr - p_ha_N` <- NULL
p_app_N$Region <- "North"
p_app_N$Scenario <- c("Baseline", "Projected", "High")
colnames(p_app_N) <- c("pest", "Region", "Scenario")

p_app_C <- as.data.frame(p_ha_C)
p_app_C$`lwr - p_ha_C`<- NULL
p_app_C$`upr - p_ha_C` <- NULL
p_app_C$Region <- "Central"
p_app_C$Scenario <- c("Baseline", "Projected", "High")
colnames(p_app_C) <- c("pest", "Region", "Scenario")

p_app_S <- as.data.frame(p_ha_S)
p_app_S$`lwr - p_ha_S` <- NULL
p_app_S$`upr - p_ha_S` <- NULL
p_app_S$Region <- "Southern"
p_app_S$Scenario <- c("Baseline", "Projected", "High")
colnames(p_app_S) <- c("pest" ,"Region", "Scenario")

p_app_E <- as.data.frame(p_ha_E)
p_app_E$`lwr - p_ha_e`<- NULL
p_app_E$`upr - p_ha_e` <- NULL
p_app_E$Region <- "East"
p_app_E$Scenario <- c("Baseline", "Projected", "High")
colnames(p_app_E) <- c("pest" ,"Region", "Scenario")

p_app_W <- as.data.frame(p_ha_W)
p_app_W$`lwr - p_ha_W` <- NULL
p_app_W$`upr - p_ha_W` <- NULL
p_app_W$Region <- "West"
p_app_W$Scenario <- c("Baseline", "Projected", "High")
colnames(p_app_W) <- c("pest", "Region", "Scenario")

p_app <- rbind(p_app_C, p_app_E, p_app_N, p_app_S, p_app_W)
rownames(p_app) <- NULL

#save tables
#=write.csv(synNapp,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/synNapp.csv")
#write.csv(p_app,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/p_app.csv")



```

```{r Create table of results - moved this code chunk to after machinery ols is calculated}

#write_csv(predict_tbl, path = "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/predict_tbl.csv")

# predict_tbl_E <- as.data.frame(cbind(p_ha_E,en_emiss_ha_E,fert_emiss_ha_E, synNuse_ha_E))
# rownames(predict_tbl_E) <- c("Baseline", "Projected",  "High_alt")
# predict_tbl_W <- as.data.frame(cbind(p_ha_W,en_emiss_ha_W,fert_emiss_ha_W, synNuse_ha_W))
# rownames(predict_tbl_W) <- c("Baseline", "Projected",  "High_alt")
# predict_tbl_S <- as.data.frame(cbind(p_ha_S,en_emiss_ha_S,fert_emiss_ha_S, synNuse_ha_S))
# rownames(predict_tbl_S) <- c("Baseline", "Projected", "High_alt")
# predict_tbl_C <- as.data.frame(cbind(p_ha_C,en_emiss_ha_C,fert_emiss_ha_C, synNuse_ha_C))
# rownames(predict_tbl_C) <- c("Baseline", "Projected",  "High_alt")
# predict_tbl_N <- as.data.frame(cbind(p_ha_N,en_emiss_ha_N,fert_emiss_ha_N, synNuse_ha_N))
# rownames(predict_tbl_N) <- c("Baseline", "Projected",  "High_alt")
# 
#  write.csv(predict_tbl_E, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/model_coefs_E.Afr.csv")
#  write.csv(predict_tbl_W, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/model_coefs_W.Afr.csv")
#  write.csv(predict_tbl_S, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results//model_coefs_S.Afr.csv")
#  write.csv(predict_tbl_N, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/model_coefs_N.Afr.csv")
#  write.csv(predict_tbl_C, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/model_coefs_C.Afr.csv")
# 
# #clean predictions
# predictions_clean <- cbind(predict_tbl_C, predict_tbl_E, predict_tbl_W, predict_tbl_N, predict_tbl_S, predict_tbl_W)
# predictions_clean <- predictions_clean[,grep("fit", colnames(predictions_clean ))] #only clean columns that show fitted values
# predictions_clean$Scenario <- c("b", "p", "h")
# predictions_clean <- melt(predictions_clean)
# predictions_clean <- predictions_clean %>% separate(variable, c("fit", "input", "ha", "region"))
# predictions_clean$fit <- NULL
# predictions_clean$ha <- NULL
# 
# write.csv(predictions_clean,"~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/Calc LUC_EnergyAg/Energy_Ag model predicted values/predictions_clean.csv")


```

```{r Calculate emissions for each input source, region, and scenario}
area_b <- scenarios %>% dplyr::select(harv_area, region, scenario) %>% filter(scenario == "b")
area_p <- scenarios %>% dplyr::select(harv_area, region, scenario) %>% filter( scenario == "p")
#area_h <- scenarios %>% dplyr::select(harv_area, region, scenario) %>% filter(scenario == "high")
area_h_alt <- scenarios %>% dplyr::select(harv_area, region, scenario) %>% filter( scenario == "h")

#Conversion factors for fertilizer and pesticides manufacturing emissions
fert_ef <- 5.66 #5.66 kg CO2 eq/kg product  is the fertilizer EF
pest_ef <- 25.5 # 25.5 kg cO2e/kg applied is the pesticides EF
kg_to_Gg <- 1/10^6  #1 Gg/1 * 10^6 kg
tons_to_Gg <- .001 #tons to Gg; formula with units : X tons applied *  Y tons CO2eq/tons product applied * .001 Gg/ ton. Y represents the pesticides emissions factor.



#total input use
as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "East"]))) * synNuse_proj_e[1] * kg_to_Gg
as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "East"]))) * pest_b_e[1] 

#Baseline
#Syn N manufacturing emissions (synthetic N Use is in kg per ha)
synNuse_emis_b_e <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "East"]))) * synNuse_b_e[1] * fert_ef * kg_to_Gg # results in manufacturing emissions for nitrogen fertilizers in Gg CO2e. "synN_b_e[1]" refers to the fitted synthetic n use/ha.
synNuse_emis_b_w <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "West"]))) * synNuse_b_w[1] * fert_ef * kg_to_Gg 
synNuse_emis_b_s <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "South"]))) * synNuse_b_s[1] * fert_ef * kg_to_Gg 
synNuse_emis_b_c <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "Central"]))) * synNuse_b_c[1] * fert_ef * kg_to_Gg 
synNuse_emis_b_n <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "North"]))) * synNuse_b_n[1] * fert_ef * kg_to_Gg 
synNuse_emis_b <- rbind(synNuse_emis_b_e, synNuse_emis_b_w, synNuse_emis_b_s, synNuse_emis_b_c, synNuse_emis_b_n)

#Syn N emissions (Gg CO2e original units, final results are in Gg CO2e )
synN_emis_b_e <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "East"]))) * synN_b_e[1] # results in syn nitrogen fertilizer emissions in Gg CO2e. "synNuse_b_e[1]" refers to the fitted synthetic n emis/ha.
synN_emis_b_w <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "West"]))) * synN_b_w[1] 
synN_emis_b_s <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "South"]))) * synN_b_s[1] 
synN_emis_b_c <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "Central"]))) * synN_b_c[1] 
synN_emis_b_n <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "North"]))) * synN_b_n[1] 
synN_emis_b <- rbind(synN_emis_b_e, synN_emis_b_w, synN_emis_b_s, synN_emis_b_c, synN_emis_b_n)

#Fuel Emissions (Gg CO2e are original units, final results are also in Gg CO2e)
f_emis_b_e <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "East"]))) * fuel_b_e[1] # results in fuel emissions in Gg CO2e. "fuel_b_e[1]" refers to the fitted  fuel emis/ha.
f_emis_b_w <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "West"]))) * fuel_b_w[1] 
f_emis_b_s <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "South"]))) * fuel_b_s[1] 
f_emis_b_c <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "Central"]))) * fuel_b_c[1] 
f_emis_b_n <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "North"]))) * fuel_b_n[1] 
f_emis_b <- rbind(f_emis_b_e, f_emis_b_w,f_emis_b_s,f_emis_b_c, f_emis_b_n)

#Pesticides manufacturing emissions (#Pesticides use is in tons per ha )
p_emis_b_e <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "East"]))) * pest_b_e[1]  * pest_ef  * tons_to_Gg # results in pesticides manufacturing emissions in Gg CO2e. "pest_b_e[1]" refers to the fitted pesticides emis/ha.
p_emis_b_w <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "West"]))) * pest_b_w[1]   * pest_ef  * tons_to_Gg
p_emis_b_s <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "South"]))) * pest_b_s[1]  * pest_ef  * tons_to_Gg
p_emis_b_c <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "Central"]))) * pest_b_c[1]  * pest_ef  * tons_to_Gg 
p_emis_b_n <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "North"]))) * pest_b_n[1]  * pest_ef  * tons_to_Gg
p_emis_b <- rbind(p_emis_b_e , p_emis_b_w,p_emis_b_s,p_emis_b_c ,p_emis_b_n)

baseline_emis <- cbind(synNuse_emis_b, synN_emis_b,f_emis_b, p_emis_b) #emissions are in #Gigagrams for each region of Africa
rownames(baseline_emis) <- c("East", "West", "Southern", "Central", "North")
colnames(baseline_emis) <- c("synN_use_base", "synN_base", "fuel_base", "pest_base")

#Projected
synNuse_emis_p_e <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "East"]))) * synNuse_proj_e[1] * fert_ef * kg_to_Gg # results in manufacturing emissions for nitrogen fertilizers in Gg CO2e. "synNuse_proj_e[1]" refers to the fitted synthetic n use/ha.
synNuse_emis_p_w <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "West"]))) * synNuse_proj_w[1] * fert_ef * kg_to_Gg
synNuse_emis_p_s <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "South"]))) * synNuse_proj_s[1] * fert_ef * kg_to_Gg
synNuse_emis_p_c <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "Central"]))) * synNuse_proj_c[1] * fert_ef * kg_to_Gg
synNuse_emis_p_n <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "North"]))) * synNuse_proj_n[1] * fert_ef * kg_to_Gg
synNuse_emis_p <- rbind(synNuse_emis_p_e, synNuse_emis_p_w, synNuse_emis_p_s, synNuse_emis_p_c, synNuse_emis_p_n)

synN_emis_p_e <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "East"]))) * synN_proj_e[1] # results in syn nitrogen fertilizer emissions in Gg CO2e. "synNuse_proj_e[1]" refers to the fitted synthetic n emis/ha.
synN_emis_p_w <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "West"]))) * synN_proj_w[1] 
synN_emis_p_s <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "South"]))) * synN_proj_s[1] 
synN_emis_p_c <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "Central"]))) * synN_proj_c[1] 
synN_emis_p_n <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "North"]))) * synN_proj_n[1] 
synN_emis_p <- rbind(synN_emis_p_e, synN_emis_p_w, synN_emis_p_s, synN_emis_p_c, synN_emis_p_n)

f_emis_p_e <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "East"]))) * fuel_proj_e[1] # results in fuel emissions in Gg CO2e. "fuel_proj_e[1]" refers to the fitted  fuel emis/ha.
f_emis_p_w <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "West"]))) * fuel_proj_w[1] 
f_emis_p_s <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "South"]))) * fuel_proj_s[1] 
f_emis_p_c <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "Central"]))) * fuel_proj_c[1] 
f_emis_p_n <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "North"]))) * fuel_proj_n[1]
f_emis_p <- rbind(f_emis_p_e, f_emis_p_w,f_emis_p_s,f_emis_p_c, f_emis_p_n)

p_emis_p_e <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "East"]))) * pest_proj_e[1] * tons_kg * pest_ef  * tons_to_Gg # results in pesticides manufacturing emissions in Gg CO2e. "pest_proj_e[1]" refers to the fitted pesticides emis/ha.
p_emis_p_w <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "West"]))) * pest_proj_w[1] * pest_ef  * tons_to_Gg
p_emis_p_s <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "South"]))) * pest_proj_s[1]  * pest_ef  * tons_to_Gg
p_emis_p_c <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "Central"]))) * pest_proj_c[1] * pest_ef  * tons_to_Gg 
p_emis_p_n <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "North"]))) * pest_proj_n[1]  * pest_ef  * tons_to_Gg
p_emis_p <- rbind(p_emis_p_e , p_emis_p_w,p_emis_p_s,p_emis_p_c ,p_emis_p_n)

proj_emis <- cbind(synNuse_emis_p, synN_emis_p,f_emis_p, p_emis_p) #emissions are in Gigagrams for each region of Africa
rownames(proj_emis) <- c("East", "West", "South", "Central", "North")
colnames(proj_emis) <- c("synN_use_proj", "synN_proj", "fuel_proj", "pest_proj")

#High_alt
synNuse_emis_h_alt_e <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "East"]))) * synNuse_h_alt_e[1] * fert_ef * kg_to_Gg # results in manufacturing emissions for nitrogen fertilizers in Gg CO2e. "synNuse_h_alt_e[1]" refers to the fitted synthetic n use/ha.
synNuse_emis_h_alt_w <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "West"]))) * synNuse_h_alt_w[1] * fert_ef * kg_to_Gg
synNuse_emis_h_alt_s <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "South"]))) * synNuse_h_alt_s[1] * fert_ef * kg_to_Gg
synNuse_emis_h_alt_c <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "Central"]))) * synNuse_h_alt_c[1] * fert_ef * kg_to_Gg
synNuse_emis_h_alt_n <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "North"]))) * synNuse_h_alt_n[1] * fert_ef * kg_to_Gg
synNuse_emis_h_alt <- rbind(synNuse_emis_h_alt_e, synNuse_emis_h_alt_w, synNuse_emis_h_alt_s, synNuse_emis_h_alt_c, synNuse_emis_h_alt_n) 

synN_emis_h_alt_e <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "East"]))) * synN_h_alt_e[1] # results in syn nitrogen fertilizer emissions in Gg CO2e. "synNuse_h_alt_e[1]" refers to the fitted synthetic n emis/ha.
synN_emis_h_alt_w <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "West"]))) * synN_h_alt_w[1] 
synN_emis_h_alt_s <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "South"]))) * synN_h_alt_s[1] 
synN_emis_h_alt_c <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "Central"]))) * synN_h_alt_c[1] 
synN_emis_h_alt_n <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "North"]))) * synN_h_alt_n[1] 
synN_emis_h_alt <- rbind(synN_emis_h_alt_e, synN_emis_h_alt_w, synN_emis_h_alt_s, synN_emis_h_alt_c, synN_emis_h_alt_n)

f_emis_h_alt_e <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "East"]))) * fuel_h_alt_e[1] # results in fuel emissions in Gg CO2e. "fuel_h_alt_e" refers to the fitted  fuel emis/ha.
f_emis_h_alt_w <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "West"]))) * fuel_h_alt_w[1] 
f_emis_h_alt_s <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "South"]))) * fuel_h_alt_s[1] 
f_emis_h_alt_c <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "Central"]))) * fuel_h_alt_c[1] 
f_emis_h_alt_n <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "North"]))) * fuel_h_alt_n[1] 
f_emis_h_alt <- rbind(f_emis_h_alt_e, f_emis_h_alt_w,f_emis_h_alt_s,f_emis_h_alt_c, f_emis_h_alt_n)

p_emis_h_alt_e <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "East"]))) * pest_h_alt_e[1] * pest_ef  * tons_to_Gg # results in pesticides manufacturing emissions in Gg CO2e. "pest_h_alt_e[1]" refers to the fitted pesticides emis/ha for east Africa.
p_emis_h_alt_w <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "West"]))) * pest_h_alt_w[1]   * pest_ef  * tons_to_Gg
p_emis_h_alt_s <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "South"]))) * pest_h_alt_s[1]  * pest_ef  * tons_to_Gg
p_emis_h_alt_c <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "Central"]))) * pest_h_alt_c[1] * pest_ef  * tons_to_Gg 
p_emis_h_alt_n <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "North"]))) * pest_h_alt_n[1] * pest_ef  * tons_to_Gg
p_emis_h_alt <- rbind(p_emis_h_alt_e , p_emis_h_alt_w, p_emis_h_alt_s, p_emis_h_alt_c , p_emis_h_alt_n)

h_alt_emis <- cbind(synNuse_emis_h_alt,synN_emis_h_alt,f_emis_h_alt, p_emis_h_alt)
rownames(h_alt_emis) <- c("East", "West", "Southern", "Central", "North")
colnames(h_alt_emis) <- c("synN_use_h_alt", "synN_h_alt", "fuel_h_alt", "pest_h_alt")
 
#Save emissions for each scenario in a .csv file
emissions <- cbind(baseline_emis, proj_emis, h_alt_emis )  # in gigagrams

#Fertilizer and pesticides application rate for Africa for each scenario
#High_alt scenario
cropland_high_afr <- colSums(area_h_alt[c(1:5),1]) #add up the regional cropland areas, the "Africa" cropland is not the same as the individual cropland areas added together (might be because our analysis excludes a few countries due to data availability)
synNuse_high_afr <- (as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "East"]))) * synNuse_h_alt_e[1]) + (as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "West"]))) * synNuse_h_alt_w[1]) + (as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "South"]))) * synNuse_h_alt_s[1]) +(as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "Central"]))) * synNuse_h_alt_c[1]) + (as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "North"]))) * synNuse_h_alt_n[1])
synNuse_ha_h_afr <- synNuse_high_afr/cropland_high_afr

#Proj Scenario
cropland_p_afr <- colSums(area_p[c(1:5),1]) #add up the regional cropland areas, the "Afria" cropland is not the same as the individual cropland areas added together (might be because our analysis excludes a few countries due to data availability)
synNuse_p_afr <- (as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "East"]))) * synNuse_proj_e[1]) + (as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "West"]))) * synNuse_proj_w[1]) + (as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "South"]))) * synNuse_proj_s[1]) +(as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "Central"]))) * synNuse_proj_c[1]) + (as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "North"]))) * synNuse_proj_n[1])
synNuse_ha_p_afr <- synNuse_p_afr/cropland_p_afr

#Baseline
cropland_b_afr <- colSums(area_b[c(1:5),1]) #add up the regional cropland areas, the "Afria" cropland is not the same as the individual cropland areas added together (might be because our analysis excludes a few countries due to data availability)
synNuse_b_afr <- (as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "East"]))) * synNuse_b_e[1]) + (as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "West"]))) * synNuse_b_w[1]) + (as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "South"]))) * synNuse_b_s[1]) +(as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "Central"]))) * synNuse_b_c[1]) + (as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "North"]))) * synNuse_b_n[1])
synNuse_ha_b_afr <- synNuse_b_afr/cropland_b_afr

#Pesticides application Africa
#high
p_h_afr <- (as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "East"]))) * pest_h_alt_e[1]) + (as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "West"]))) * pest_h_alt_w[1]) + (as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "South"]))) * pest_h_alt_s[1]) + (as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "Central"]))) * pest_h_alt_c[1]) + (as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "North"]))) * pest_h_alt_n[1])
p_ha_h_afr <- p_h_afr/cropland_high_afr
#proj
pest_p_afr <- (as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "East"]))) * pest_proj_e[1]) + (as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "West"]))) * pest_proj_w[1]) + (as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "South"]))) * pest_proj_s[1]) +(as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "Central"]))) * pest_proj_c[1]) + (as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "North"]))) * pest_proj_n[1])
pest_ha_p_afr <- pest_p_afr/cropland_p_afr
#b
pest_b_afr <- (as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "East"]))) * pest_b_e[1]) + (as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "West"]))) * pest_b_w[1]) + (as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "South"]))) * pest_b_s[1]) +(as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "Central"]))) * pest_b_c[1]) + (as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "North"]))) * pest_b_n[1])
pest_ha_b_afr <- pest_b_afr/cropland_b_afr

```

```{r Sanity Check on parameters - optional for running}

#Check to see that that the model fitted values match the log(actual values) in the regression dataset, values should fall around 1:1 line

# plot(x = log(na.omit(filter_reg$p_ha)), y = p.ols$fitted.values, xlab = "True values", ylab = "Model Fitted values", main = "Regression fits of pesticide/ha values")
# abline(b=1, a=0) #values fall around this 1:1 line 
# 
# 
# plot(x = log(na.omit(filter_f_reg$en_emiss_ha)), y = fuel.ols$fitted.values, xlab = "True values", ylab = "Model Fitted values", main = "Regression fits of fuel/ha values")
#  abline(b=1, a=0) #values should fall around this line, some values are scattered to the left 
# 
# 
# plot(x = log(na.omit(filter_syn_reg$fert_emiss_ha)), y = syn_n.ols$fitted.values, xlab = "True values", ylab = "Model Fitted values", main = "Regression fits of synN/ha values")
# abline(b=1, a=0) #values fall around this 1:1 line 
# 
# plot(log(na.omit(filter_fert_use_reg$fert_use_ha)), fert_use.ols$fitted.values,xlab = "True values", ylab = "Model Fitted values", main = "Regression fits of synN use/ha values"  )
# abline(b=1, a=0) #values fall around this 1:1 line 
```


```{r Set up OLS for Machinery Emissions}

#Calculate Energy Embodied in Machinery Emissions 
machinery_energy <- read_csv("~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/raw_data/Machinery_Emissions.csv")
#units for all fuel and energy sources listed under the item column is in Terajoules
#machinery_energy <- Machinery_Emissions
machinery_energy <- machinery_energy %>%
  distinct() %>%
  tidyr::spread(Item, Value)


#interpolate missing values using Last one carried forward (LOCF)
machinery_energy <-  machinery_energy %>% group_by(Country) %>% mutate(`Gas-Diesel oil`  = na.locf(`Gas-Diesel oil`, na.rm = FALSE))
machinery_energy <-  machinery_energy %>% group_by(Country) %>% mutate(`Motor Gasoline`  = na.locf(`Motor Gasoline`, na.rm = FALSE))
machinery_energy <-  machinery_energy %>% group_by(Country) %>% mutate(`Gas-diesel oils used in fisheries`  = na.locf(`Gas-diesel oils used in fisheries`, na.rm = FALSE))
machinery_energy <- na.omit(machinery_energy) #remove missing values

#substract fisheries use for gas-diesel
machinery_energy$`Gas-Diesel oil` <- machinery_energy$`Gas-Diesel oil` - machinery_energy$`Gas-diesel oils used in fisheries` #subtracts fishery gas-diesel from total gas-diesel, to better calculate gas-diesel used in crop production
machinery_energy$`Gas-diesel oils used in fisheries` <- NULL

machinery_energy[machinery_energy <= 0] <- NA  #sets 0 and negative values to NA since those are not possible values

#Calculate emissions using Woods et al. and Michael Goeff's method. And, multiply by TPES EF for Africa and convert to Gigagrams
tpes_ef <- 34 #emissions factor for primary energy supply for Africa (34 tons CO2 eq/Terajoules), carbon intensity of energy mix
gas_machinery <- 0.4 #Machinery emissions is equivalent to 40% of Gas-diesel + Motor gasoline use (gas diesel + motor gasoline use is in terajoules)

machinery_emissions <- machinery_energy %>% mutate(Machinery.Emissions = ((`Gas-Diesel oil` + `Motor Gasoline`) * gas_machinery) * tpes_ef * tons_to_Gg)  

#Combine reg data  (yields and cropland data) with machinery emissions data to calculate machinery emissions/ha by country,year

colnames(machinery_emissions) <- c("country", "year", "gas-diesel oil", "motor-gasoline", "machinery.emissions")
reg_m <- full_join(reg, machinery_emissions)
reg_m <- reg_m %>% dplyr::select(year,country,cropland_ha, production_kcal, machinery.emissions)
reg_m$country_rename <- reg_m$country


#Aggregate reg_m data by region, rename the country names according to their region in Africa.
reg_m$country_rename[reg_m$country_rename %in% E_Afr] <-  "E_Afr"
reg_m$country_rename[reg_m$country_rename %in% W_Afr] <-  "W_Afr"
reg_m$country_rename[reg_m$country_rename %in% C_Afr] <-  "C_Afr"
reg_m$country_rename[reg_m$country_rename %in% S_Afr] <-  "S_Afr"
reg_m$country_rename[reg_m$country_rename %in% N_Afr] <-  "N_Afr"

reg_m_E <- dplyr::filter(reg_m,reg_m$country_rename == "E_Afr" )
reg_m_W <- dplyr::filter(reg_m,reg_m$country_rename == "W_Afr" )
reg_m_C <- dplyr::filter(reg_m,reg_m$country_rename == "C_Afr" )
reg_m_S <- dplyr::filter(reg_m,reg_m$country_rename == "S_Afr" )
reg_m_N <- dplyr::filter(reg_m,reg_m$country_rename == "N_Afr" )

#For Central Africa, North Africa all machinery emissions are NA. East, South, and West Africa have non-NA values.

#Calculate aggregate values for each region
reg_E_aggregate <- reg_m_E %>%
  dplyr::select(year, cropland_ha,production_kcal, machinery.emissions) %>% 
  dplyr::group_by(year) %>%
  dplyr::summarise_all(sum, na.rm = TRUE)
reg_W_aggregate <- reg_m_W %>%
  dplyr::select(year, cropland_ha,production_kcal, machinery.emissions) %>% 
  dplyr::group_by(year) %>%
  dplyr::summarise_all(sum, na.rm = TRUE)
reg_S_aggregate <- reg_m_S %>%
  dplyr::select(year, cropland_ha,production_kcal,machinery.emissions) %>% 
  dplyr::group_by(year) %>%
  dplyr::summarise_all(sum, na.rm = TRUE)
reg_N_aggregate <- reg_m_N %>%
  dplyr::select(year, cropland_ha,production_kcal, machinery.emissions) %>% 
  dplyr::group_by(year) %>%
  dplyr::summarise_all(sum, na.rm = TRUE)
reg_C_aggregate <- reg_m_C %>%
  dplyr::select(year, cropland_ha,production_kcal, machinery.emissions) %>% 
  dplyr::group_by(year) %>%
  dplyr::summarise_all(sum, na.rm = TRUE)

reg_E_aggregate$m_ha <- reg_E_aggregate$machinery.emissions/reg_E_aggregate$cropland_ha
reg_W_aggregate$m_ha <- reg_W_aggregate$machinery.emissions/reg_W_aggregate$cropland_ha
reg_S_aggregate$m_ha <- reg_S_aggregate$machinery.emissions/reg_S_aggregate$cropland_ha
reg_C_aggregate$m_ha <- reg_C_aggregate$machinery.emissions/reg_C_aggregate$cropland_ha
reg_N_aggregate$m_ha <- reg_N_aggregate$machinery.emissions/reg_N_aggregate$cropland_ha

reg_E_aggregate$yield <- reg_E_aggregate$production_kcal/reg_E_aggregate$cropland_ha
reg_W_aggregate$yield <- reg_W_aggregate$production_kcal/reg_W_aggregate$cropland_ha
reg_S_aggregate$yield <- reg_S_aggregate$production_kcal/reg_S_aggregate$cropland_ha
reg_C_aggregate$yield <- reg_C_aggregate$production_kcal/reg_C_aggregate$cropland_ha
reg_N_aggregate$yield <- reg_N_aggregate$production_kcal/reg_N_aggregate$cropland_ha

reg_E_aggregate$country <- "East"
reg_W_aggregate$country <- "West"
reg_S_aggregate$country <- "Southern"
reg_C_aggregate$country<- "Central"
reg_N_aggregate$country <- "North"

#join aggregate machinery emissions data for Africa regions with non-Africa dataframe
reg_other_country <- reg_other_country %>% dplyr::select(year, country)
reg_other_country <- inner_join(reg_other_country, reg_m) # add machinery values to non-Africa dataframe

reg_all_countries <- full_join(reg_other_country ,reg_E_aggregate )
reg_all_countries <- full_join(reg_all_countries ,reg_W_aggregate )
reg_all_countries <- full_join(reg_all_countries ,reg_S_aggregate )
reg_all_countries <- full_join(reg_all_countries,reg_C_aggregate )
reg_all_countries <- full_join(reg_all_countries ,reg_N_aggregate )

reg_all_countries$yield <- reg_all_countries$production_kcal/reg_all_countries$cropland_ha
reg_all_countries$m_ha <- reg_all_countries$machinery.emissions/reg_all_countries$cropland_ha

#filter out outlier data
filter_reg_m <- filter(reg_all_countries, reg_all_countries$yield < 20000000)
# e.plot <- dplyr::filter(filter_reg_m, filter_reg_m$country == "East")
# w.plot <- dplyr::filter(filter_reg_m, filter_reg_m$country == "West")
# c.plot <- dplyr::filter(filter_reg_m, filter_reg_m$country == "Central")
# s.plot <- dplyr::filter(filter_reg_m, filter_reg_m$country == "South")
# n.plot <- dplyr::filter(filter_reg_m, filter_reg_m$country == "North")

#plot(e.plot$production_kcal/e.plot$cropland_ha, e.plot$m_ha)
#plot(w.plot$production_kcal/w.plot$cropland_ha, w.plot$m_ha)
#plot(c.plot$production_kcal/c.plot$cropland_ha, c.plot$m_ha) #no machinery emissions data
#plot(s.plot$production_kcal/s.plot$cropland_ha, s.plot$m_ha)
#plot(n.plot$production_kcal/n.plot$cropland_ha, n.plot$m_ha)


#create columsn for machinery emissions per hectare, and for yield
#filter_reg_m_yrs <- filter(filter_reg_m, filter_reg_m$year >  1996 )

#filter_reg_m$m_ha <- filter_reg_m$machinery.emissions/filter_reg_m$cropland_ha 
#filter_reg_m$yield <- filter_reg_m$production_kcal/filter_reg_m$cropland_ha

#filter_reg_m_yrs$m_ha <- filter_reg_m_yrs$machinery.emissions/filter_reg_m_yrs$cropland_ha 
#filter_reg_m_yrs$yield <- filter_reg_m_yrs$production_kcal/filter_reg_m_yrs$cropland_ha

#filter out rows with 0 or NA machinery emissions per hectare since 0s are not plausible and NAs will be dropped in regression anyway
filter_reg_m <- filter(filter_reg_m, m_ha >0)
filter_reg_m <- filter_reg_m[!is.na(filter_reg_m$m_ha),]

#filter_reg_m_yrs <- filter(filter_reg_m_yrs, m_ha >0)
#filter_reg_m_yrs <- filter_reg_m_yrs[!is.na(filter_reg_m_yrs$m_ha),]
#clean country column names
# filter_reg_m$country <- filter_reg_m$country_rename
# filter_reg_m$country_rename <- NULL
# filter_reg_m[filter_reg_m=="Southern"] <- "South"

#filter_reg_m_yrs[filter_reg_m_yrs=="Southern"] <- "South"
m.ols <- lm(filter_reg_m, formula = log(m_ha) ~ log(yield) + factor(country)) #create ols model so energy embodied in machinery emissions can be predicted for scenarios based on yields, "factor(Rename)" has country coding to reduce bias in estimates

#for sensitivity analysis
#m.ols <- lm(filter_reg_m, formula = m_ha ~ yield + factor(country)) 

#m.ols <- lm(filter_reg_m_yrs, formula = log(m_ha) ~ log(yield) + factor(country)) #sensitivty analysis 
```

```{r Calculate Machinery emissions}
#Make predictions on machinery emissions for each scenario
#based on the simple linear regression model, the predict function predicts machinery emissions values for the baseline scenario for East Africa. "lwr" and "upr" represent the lower and the upper confidence limits for the predicted values, respectively. By default the function produces the 95% confidence limits.

#East Africa - machinery emis/ha
 machinery_b_e <- exp(predict(m.ols , newdata  = b_e, interval = "confidence", level = 0.95))
 machinery_proj_e <- exp(predict(m.ols , newdata  = p_e,  interval = "confidence", level = 0.95))
 machinery_h_alt_e <- exp(predict(m.ols, newdata  = h_alt_e,  interval = "confidence", level = 0.95))

#sensitivity analysis, linear model
# machinery_b_e <- predict(m.ols , newdata  = b_e, interval = "confidence", level = 0.95)
# machinery_proj_e <- predict(m.ols , newdata  = p_e,  interval = "confidence", level = 0.95)
# machinery_h_alt_e <- predict(m.ols, newdata  = h_alt_e,  interval = "confidence", level = 0.95)

machinery_ha_E <- rbind(machinery_b_e  ,machinery_proj_e, machinery_h_alt_e)
colnames(machinery_ha_E) <- c("fit_machinery_ha_e","lwr_machinery_ha_e", "upr_machinery_ha_e")

#Make predictions on  machinery emissions/ha for each scenario for West Africa
 machinery_b_w <- exp(predict(m.ols , newdata  = b_w, interval = "confidence", level = 0.95))
 machinery_proj_w <- exp(predict(m.ols , newdata  = p_w,  interval = "confidence", level = 0.95))
 machinery_h_alt_w <- exp(predict(m.ols , newdata  = h_alt_w,  interval = "confidence", level = 0.95))

#sensitivity analysis, linear model
# machinery_b_w <- predict(m.ols , newdata  = b_w, interval = "confidence", level = 0.95)
# machinery_proj_w <- predict(m.ols , newdata  = p_w,  interval = "confidence", level = 0.95)
# machinery_h_alt_w <- predict(m.ols , newdata  = h_alt_w,  interval = "confidence", level = 0.95)

machinery_ha_W <- rbind(machinery_b_w, machinery_proj_w ,  machinery_h_alt_w)
colnames(machinery_ha_W) <- c("fit_machinery_ha_w","lwr_machinery_ha_w", "upr_machinery_ha_w")


#Make predictions on machinery emissions/ha for each scenario for Southern Africa
b_s$country <- "Southern"
p_s$country <- "Southern"
h_alt_s$country <- "Southern"
machinery_b_s <- exp(predict(m.ols , newdata  = b_s, interval = "confidence", level = 0.95))
machinery_proj_s <- exp(predict(m.ols , newdata  = p_s,  interval = "confidence", level = 0.95))
machinery_h_alt_s <- exp(predict(m.ols , newdata  = h_alt_s,  interval = "confidence", level = 0.95))

#sensitivity analysis, linear model
# machinery_b_s <- predict(m.ols , newdata  = b_s, interval = "confidence", level = 0.95)
# machinery_proj_s <- predict(m.ols , newdata  = p_s,  interval = "confidence", level = 0.95)
# machinery_h_alt_s <- predict(m.ols , newdata  = h_alt_s,  interval = "confidence", level = 0.95)

machinery_ha_S <- rbind(machinery_b_s , machinery_proj_s , machinery_h_alt_s)
colnames(machinery_ha_S) <- c("fit_machinery_ha_s","lwr_machinery_ha_s", "upr_machinery_ha_s")


#Central and North Africa have missing data (NA values) for machinery emissions for all countries. So there is no data to make predictions. Using an average of Southern, East, and West Africa's machinery emissions for each scenario.

machinery_b_s <- as.data.frame(machinery_b_s)
machinery_b_e <- as.data.frame(machinery_b_e)
machinery_b_w <- as.data.frame(machinery_b_w)

machinery_proj_s <- as.data.frame(machinery_proj_s)
machinery_proj_e <- as.data.frame(machinery_proj_e)
machinery_proj_w <- as.data.frame(machinery_proj_w)

#machinery_h_s <- as.data.frame(machinery_h_s)
#machinery_h_e <- as.data.frame(machinery_h_e)
#machinery_h_w <- as.data.frame(machinery_h_w)

machinery_h_alt_s <- as.data.frame(machinery_h_alt_s)
machinery_h_alt_e <- as.data.frame(machinery_h_alt_e)
machinery_h_alt_w <- as.data.frame(machinery_h_alt_w)

machinery_b_c <- as.data.frame(mean(machinery_b_s$fit, machinery_b_e$fit, machinery_b_w$fit))
machinery_proj_c <- as.data.frame(mean(machinery_proj_e$fit, machinery_proj_s$fit, machinery_proj_w$fit))
machinery_h_alt_c <- as.data.frame(mean(machinery_h_alt_e$fit, machinery_h_alt_s$fit, machinery_h_alt_w$fit))


machinery_b_c$lwr <- mean(machinery_b_s$lwr, machinery_b_e$lwr, machinery_b_w$lwr)
machinery_proj_c$lwr <- mean(machinery_proj_e$lwr, machinery_proj_s$lwr, machinery_proj_w$lwr)
machinery_h_alt_c$lwr <- mean(machinery_h_alt_e$lwr, machinery_h_alt_s$lwr, machinery_h_alt_w$lwr)

machinery_b_c$upr <- mean(machinery_b_s$upr, machinery_b_e$upr, machinery_b_w$upr)
machinery_proj_c$upr<- mean(machinery_proj_e$upr, machinery_proj_s$upr, machinery_proj_w$upr)
machinery_h_alt_c$upr <- mean(machinery_h_alt_e$upr, machinery_h_alt_s$upr, machinery_h_alt_w$upr)

colnames(machinery_b_c) <- c("fit", "lwr", "upr")
colnames(machinery_proj_c) <- c("fit", "lwr", "upr")
#colnames(machinery_h_c) <- c("fit", "lwr", "upr")
colnames(machinery_h_alt_c) <- c("fit", "lwr", "upr")
machinery_ha_c <- rbind(machinery_b_c, machinery_proj_c, machinery_h_alt_c)
colnames(machinery_ha_c) <- c("fit_machinery_ha_c","lwr_machinery_ha_c", "upr_machinery_ha_c")
rownames(machinery_ha_c) <- c("baseline", "proj" , "high_alt")
machinery_ha_n <- machinery_ha_c
colnames(machinery_ha_n) <- c("fit_machinery_ha_n","lwr_machinery_ha_n", "upr_machinery_ha_n")
machinery_b_n <- machinery_ha_n[1,]
rownames(machinery_b_n) <- NULL
machinery_proj_n <- machinery_ha_n[2,]
rownames(machinery_proj_n) <- NULL
#machinery_h_n <- machinery_ha_n[3,]
#rownames(machinery_h_n) <- NULL
machinery_h_alt_n <- machinery_ha_n[3,]
rownames(machinery_h_alt_n) <- NULL

#add machinery emisions data to predictions_clean
predict_tbl_E <- as.data.frame(cbind(p_ha_E,en_emiss_ha_E,fert_emiss_ha_E, synNuse_ha_E, machinery_ha_E))
rownames(predict_tbl_E) <- c("Baseline", "Projected",  "High_alt")
predict_tbl_W <- as.data.frame(cbind(p_ha_W,en_emiss_ha_W,fert_emiss_ha_W, synNuse_ha_W, machinery_ha_W))
rownames(predict_tbl_W) <- c("Baseline", "Projected",  "High_alt")
predict_tbl_S <- as.data.frame(cbind(p_ha_S,en_emiss_ha_S,fert_emiss_ha_S, synNuse_ha_S, machinery_ha_S))
rownames(predict_tbl_S) <- c("Baseline", "Projected", "High_alt")
predict_tbl_C <- as.data.frame(cbind(p_ha_C,en_emiss_ha_C,fert_emiss_ha_C, synNuse_ha_C, machinery_ha_c))
rownames(predict_tbl_C) <- c("Baseline", "Projected",  "High_alt")
predict_tbl_N <- as.data.frame(cbind(p_ha_N,en_emiss_ha_N,fert_emiss_ha_N, synNuse_ha_N, machinery_ha_n))
rownames(predict_tbl_N) <- c("Baseline", "Projected",  "High_alt")

 write.csv(predict_tbl_E, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/model_coefs_E.Afr.csv")
 write.csv(predict_tbl_W, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/model_coefs_W.Afr.csv")
 write.csv(predict_tbl_S, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results//model_coefs_S.Afr.csv")
 write.csv(predict_tbl_N, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/model_coefs_N.Afr.csv")
 write.csv(predict_tbl_C, "~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/model_coefs_C.Afr.csv")

#clean predictions
predictions_clean <- cbind(predict_tbl_C, predict_tbl_E, predict_tbl_W, predict_tbl_N, predict_tbl_S, predict_tbl_W)
predictions_clean <- predictions_clean[,grep("fit", colnames(predictions_clean ))] #only clean columns that show fitted values
predictions_clean$Scenario <- c("b", "p", "h")
predictions_clean <- melt(predictions_clean)
predictions_clean <- predictions_clean %>% separate(variable, c("fit", "input", "ha", "region"))
predictions_clean$fit <- NULL
predictions_clean$ha <- NULL

write.csv(predictions_clean,"~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/Calc LUC_EnergyAg/Energy_Ag model predicted values/predictions_clean.csv")

#Multiply predictions by ha of cropland area for each scenario to get total machinery emissions 
#baseline scenario
m_emis_b_e  <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "East"]))) * machinery_b_e[1] # results in embodied energy emissions from machinery in Gg CO2e. 
m_emis_b_w <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "West"]))) * machinery_b_w[1]  
m_emis_b_s <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "South"]))) * machinery_b_s[1] 
m_emis_b_c <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "Central"]))) * machinery_b_c[1] 
m_emis_b_n <- as.numeric(matrix(unlist(area_b$harv_area[area_b$region == "North"]))) * machinery_b_n[1] 
rownames(m_emis_b_c) <- NULL
rownames(m_emis_b_n) <- NULL
colnames(m_emis_b_n) <- "fit"
m_emis_b <- rbind(m_emis_b_e, m_emis_b_w, m_emis_b_s , m_emis_b_c , m_emis_b_n)
rownames(m_emis_b) <- c("East", "West", "Southern", "Central", "North")

#projected scenario
m_emis_p_e  <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "East"]))) * machinery_proj_e[1] # results in embodied energy emissions from machinery in Gg CO2e. 
m_emis_p_w <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "West"]))) * machinery_proj_w[1]  
m_emis_p_s <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "South"]))) * machinery_proj_s[1] 
m_emis_p_c <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "Central"]))) * machinery_proj_c[1] 
m_emis_p_n <- as.numeric(matrix(unlist(area_p$harv_area[area_p$region == "North"]))) * machinery_proj_n[1] 

rownames(m_emis_p_e) <- NULL
rownames(m_emis_p_w) <- NULL
rownames(m_emis_p_s) <- NULL
rownames(m_emis_p_c) <- NULL
rownames(m_emis_p_n) <- NULL
colnames(m_emis_p_n) <- "fit"
m_emis_p <- rbind(m_emis_p_e  , m_emis_p_w, m_emis_p_s , m_emis_p_c , m_emis_p_n)
rownames(m_emis_p) <- c("East", "West", "Southern", "Central", "North")

#high alt scenario
m_emis_h_alt_e  <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "East"]))) * machinery_h_alt_e[1] # results in embodied energy emissions from machinery in Gg CO2e. 
m_emis_h_alt_w <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "West"]))) * machinery_h_alt_w[1]  
m_emis_h_alt_s <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "South"]))) * machinery_h_alt_s[1] 
m_emis_h_alt_c <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "Central"]))) * machinery_h_alt_c[1] 
m_emis_h_alt_n <- as.numeric(matrix(unlist(area_h_alt$harv_area[area_h_alt$region == "North"]))) * machinery_h_alt_n[1] 

rownames(m_emis_h_alt_e) <- NULL
rownames(m_emis_h_alt_w) <- NULL
rownames(m_emis_h_alt_s) <- NULL
rownames(m_emis_h_alt_c) <- NULL
rownames(m_emis_h_alt_n) <- NULL
colnames(m_emis_h_alt_n) <-  "fit"
m_emis_h_alt <- rbind(m_emis_h_alt_e  , m_emis_h_alt_w, m_emis_h_alt_s , m_emis_h_alt_c , m_emis_h_alt_n)

machinery_emis <- cbind(m_emis_b, m_emis_p, m_emis_h_alt)
colnames(machinery_emis) <- c("m_base", "m_proj", "m_h_alt")
rownames(machinery_emis) <- c("East","West","Southern","Central","North")
Energy_emis <- cbind(emissions,machinery_emis)
Energy_emis <- as.data.frame(t(Energy_emis))
temp <- rownames(Energy_emis)
Energy_emis <- Energy_emis %>% mutate(Africa = rowSums(Energy_emis))
rownames(Energy_emis) <- temp #in gigagrams
#write.csv(Energy_emis,"~/Google Drive/My Drive/Food & Farming/Energy in ag/Energy and GHG Analysis (2019)/Analysis/energy_ag_analysis/Results/Energy_emissions.csv")
```


```{r Add Machinery energy adn emissions predictions to energy predicted values table }

predict_tbl_C <- na.omit(predict_tbl_C)
predict_tbl_E <- na.omit(predict_tbl_E)
predict_tbl_W <- na.omit(predict_tbl_W)
predict_tbl_N <- na.omit(predict_tbl_N)
predict_tbl_S <- na.omit(predict_tbl_S)
machinery_ha_E <- na.omit(machinery_ha_E)
machinery_ha_S<- na.omit(machinery_ha_S)
machinery_ha_W <- na.omit(machinery_ha_W)

predict_tbl_C <- cbind(predict_tbl_C, machinery_ha_c)
predict_tbl_E <- cbind(predict_tbl_E, machinery_ha_E)
predict_tbl_W <- cbind(predict_tbl_W, machinery_ha_W)
predict_tbl_N <- cbind(predict_tbl_N, machinery_ha_n)
predict_tbl_S <- cbind(predict_tbl_S, machinery_ha_S)

predict_tbl_C$Scenario <- rownames(predict_tbl_C)
predict_tbl_N$Scenario <- rownames(predict_tbl_N)
predict_tbl_S$Scenario <- rownames(predict_tbl_S)
predict_tbl_E$Scenario <- rownames(predict_tbl_E)
predict_tbl_W$Scenario <- rownames(predict_tbl_W)

predict_tbl_C <- melt(predict_tbl_C)
predict_tbl_S <- melt(predict_tbl_S)
predict_tbl_W <- melt(predict_tbl_W)
predict_tbl_E <- melt(predict_tbl_E)
predict_tbl_N <- melt(predict_tbl_N)


predict_tbl_C <- predict_tbl_C %>% separate(variable, c("val_type", "Energy_Source"), "-") #val_type is type of value from model output which is either a fitted value, or the 95% lower or upper CI intervals
predict_tbl_S <- predict_tbl_S %>% separate(variable, c("val_type", "Energy_Source"), "-")
predict_tbl_W <- predict_tbl_W %>% separate(variable, c("val_type", "Energy_Source"), "-")
predict_tbl_E <- predict_tbl_E %>% separate(variable, c("val_type", "Energy_Source"), "-")
predict_tbl_N <- predict_tbl_N %>% separate(variable, c("val_type", "Energy_Source"), "-")

predict_tbl_C <- na.omit(predict_tbl_C)
predict_tbl_S <- na.omit(predict_tbl_S)
predict_tbl_W <- na.omit(predict_tbl_W)
predict_tbl_E <- na.omit(predict_tbl_E)
predict_tbl_N <- na.omit(predict_tbl_N)

#Rename energy sources in predict tbls
predict_tbl_C$Energy_Source <- str_replace(predict_tbl_C$Energy_Source, "p_ha_C","Manufacturing Pesticides")
predict_tbl_C$Energy_Source <- str_replace(predict_tbl_C$Energy_Source, "en_emiss_ha_C","On-Farm Fuel")
predict_tbl_C$Energy_Source  <- str_replace(predict_tbl_C$Energy_Source , "fert_emiss_ha_C","Synthetic N")
predict_tbl_C$Energy_Source  <- str_replace(predict_tbl_C$Energy_Source , "synNuse_ha_c","Manufacturing Fertilizers")
predict_tbl_C$Energy_Source  <- str_replace(predict_tbl_C$Energy_Source , " machinery_ha_c","Embodied Energy in Machinery")

predict_tbl_E$Energy_Source <- str_replace(predict_tbl_E$Energy_Source, "p_ha_e","Manufacturing Pesticides")
predict_tbl_E$Energy_Source <- str_replace(predict_tbl_E$Energy_Source, "en_emiss_ha_e","On-Farm Fuel")
predict_tbl_E$Energy_Source  <- str_replace(predict_tbl_E$Energy_Source , "fert_emiss_ha_E","Synthetic N")
predict_tbl_E$Energy_Source  <- str_replace(predict_tbl_E$Energy_Source ,  "syn_Nuse_ha_e","Manufacturing Fertilizers")
predict_tbl_E$Energy_Source  <- str_replace(predict_tbl_E$Energy_Source , " machinery_ha_e","Embodied Energy in Machinery")

predict_tbl_W$Energy_Source <- str_replace(predict_tbl_W$Energy_Source, "p_ha_W","Manufacturing Pesticides")
predict_tbl_W$Energy_Source <- str_replace(predict_tbl_W$Energy_Source, "en_emiss_ha_W","On-Farm Fuel")
predict_tbl_W$Energy_Source  <- str_replace(predict_tbl_W$Energy_Source , "fert_emiss_ha_W","Synthetic N")
predict_tbl_W$Energy_Source  <- str_replace(predict_tbl_W$Energy_Source ,  "synNuse_ha_w","Manufacturing Fertilizers")
predict_tbl_W$Energy_Source  <- str_replace(predict_tbl_W$Energy_Source ,  "syn_Nuse_ha_w","Manufacturing Fertilizers")
predict_tbl_W$Energy_Source  <- str_replace(predict_tbl_W$Energy_Source , "machinery_ha_w","Embodied Energy in Machinery")

predict_tbl_N$Energy_Source <- str_replace(predict_tbl_N$Energy_Source, "p_ha_N","Manufacturing Pesticides")
predict_tbl_N$Energy_Source <- str_replace(predict_tbl_N$Energy_Source, "en_emiss_ha_N","On-Farm Fuel")
predict_tbl_N$Energy_Source  <- str_replace(predict_tbl_N$Energy_Source , "fert_emiss_ha_N","Synthetic N")
predict_tbl_N$Energy_Source  <- str_replace(predict_tbl_N$Energy_Source ,  " synNuse_ha_n","Manufacturing Fertilizers")
predict_tbl_N$Energy_Source  <- str_replace(predict_tbl_N$Energy_Source , "machinery_ha_n","Embodied Energy in Machinery")

predict_tbl_S$Energy_Source <- str_replace(predict_tbl_S$Energy_Source, "p_ha_S","Manufacturing Pesticides")
predict_tbl_S$Energy_Source <- str_replace(predict_tbl_S$Energy_Source, "en_emiss_ha_S","On-Farm Fuel")
predict_tbl_S$Energy_Source  <- str_replace(predict_tbl_S$Energy_Source , "fert_emiss_ha_S","Synthetic N")
predict_tbl_S$Energy_Source  <- str_replace(predict_tbl_S$Energy_Source ,  " synNuse_ha_s","Manufacturing Fertilizers")
predict_tbl_S$Energy_Source  <- str_replace(predict_tbl_S$Energy_Source , "machinery_ha_s","Embodied Energy in Machinery")


```

```{r Pull out lower and upper confidence intervals from model predictions}


#Lwr and Upr values represent 95% confidence intervals or range of values. First convert to standard error bars, then multiply by cropland values and relevant conversion/emissions factor values. 

#Calculate means for standard error
#predict_tbl_C$mean_p <- rowMeans(cbind(predict_tbl_C$`lwr - p_ha_C`, predict_tbl_C$`upr - p_ha_C`)) 
#predict_tbl_C$mean_f <- rowMeans(cbind(predict_tbl_C$`lwr - en_emiss_ha_C`, predict_tbl_C$`upr - en_emiss_ha_C`)) 
#predict_tbl_C$mean_synNuse <- rowMeans(cbind(predict_tbl_C$`lwr - synNuse_ha_c`, predict_tbl_C$`upr - synNuse_ha_c`)) 
#predict_tbl_C$mean_synN <- rowMeans(cbind(predict_tbl_C$`lwr - fert_emiss_ha_C`, predict_tbl_C$`upr - fert_emiss_ha_C`)) 
#predict_tbl_C$mean_m <- rowMeans(cbind(predict_tbl_C$`lwr - machinery_ha_c`, predict_tbl_C$`upr - machinery_ha_c`)) 

# predict_tbl_N$mean_p <- rowMeans(cbind(predict_tbl_N$`lwr - p_ha_N`, predict_tbl_N$`upr - p_ha_N`)) 
# predict_tbl_N$mean_f <- rowMeans(cbind(predict_tbl_N$`lwr - en_emiss_ha_N`, predict_tbl_N$`upr - en_emiss_ha_N`)) 
# predict_tbl_N$mean_synNuse <- rowMeans(cbind(predict_tbl_N$`lwr - synNuse_ha_n`, predict_tbl_N$`upr - synNuse_ha_n`)) 
# predict_tbl_N$mean_synN <- rowMeans(cbind(predict_tbl_N$`lwr - fert_emiss_ha_N`, predict_tbl_N$`upr - fert_emiss_ha_N`)) 
# predict_tbl_N$mean_m <- rowMeans(cbind(predict_tbl_N$`lwr - machinery_ha_n`, predict_tbl_N$`upr - machinery_ha_n`)) 

# predict_tbl_W$mean_p <- rowMeans(cbind(predict_tbl_W$`lwr - p_ha_W`, predict_tbl_W$`upr - p_ha_W`)) 
# predict_tbl_W$mean_f <- rowMeans(cbind(predict_tbl_W$`lwr - en_emiss_ha_W`, predict_tbl_W$`upr - en_emiss_ha_W`)) 
# predict_tbl_W$mean_synNuse <- rowMeans(cbind(predict_tbl_W$`lwr - syn_Nuse_ha_w`, predict_tbl_W$`upr - syn_Nuse_ha_w`)) 
# predict_tbl_W$mean_synN <- rowMeans(cbind(predict_tbl_W$`lwr - fert_emiss_ha_W`, predict_tbl_W$`upr - fert_emiss_ha_W`)) 
# predict_tbl_W$mean_m <- rowMeans(cbind(predict_tbl_W$`lwr -machinery_ha_w`, predict_tbl_W$`upr - machinery_ha_w`))
# 
# predict_tbl_S$mean_p <- rowMeans(cbind(predict_tbl_S$`lwr - p_ha_S`, predict_tbl_S$`upr - p_ha_S`)) 
# predict_tbl_S$mean_f <- rowMeans(cbind(predict_tbl_S$`lwr - en_emiss_ha_S`, predict_tbl_S$`upr - en_emiss_ha_S`)) 
# predict_tbl_S$mean_synNuse <- rowMeans(cbind(predict_tbl_S$`lwr - synNuse_ha_s`, predict_tbl_S$`upr - synNuse_ha_s`)) 
# predict_tbl_S$mean_synN <- rowMeans(cbind(predict_tbl_S$`lwr - fert_emiss_ha_S`, predict_tbl_S$`upr - fert_emiss_ha_S`)) 
# predict_tbl_S$mean_m <- rowMeans(cbind(predict_tbl_S$`lwr - machinery_ha_s`, predict_tbl_S$`upr - machinery_ha_s`))
# 
# predict_tbl_E$mean_p <- rowMeans(cbind(predict_tbl_E$`lwr - p_ha_e`, predict_tbl_E$`upr - p_ha_e`)) 
# predict_tbl_E$mean_f <- rowMeans(cbind(predict_tbl_E$`lwr - en_emiss_ha_e`, predict_tbl_E$`upr - en_emiss_ha_e`)) 
# predict_tbl_E$mean_synNuse <- rowMeans(cbind(predict_tbl_E$`lwr - syn_Nuse_ha_e`, predict_tbl_E$`upr - syn_Nuse_ha_e`)) 
# predict_tbl_E$mean_synN <- rowMeans(cbind(predict_tbl_E$`lwr - fert_emiss_ha_E`, predict_tbl_E$`upr - fert_emiss_ha_E`)) 
# predict_tbl_E$mean_m <- rowMeans(cbind(predict_tbl_E$`lwr - machinery_ha_e`, predict_tbl_E$`upr - machinery_ha_e`))
# 
# #predict_tbl$mean_p <- rowMeans(cbind(predict_tbl$`lwr - p_ha`, predict_tbl$`upr - p_ha`)) 
# #predict_tbl$mean_f <- rowMeans(cbind(predict_tbl$`lwr - en_emiss_ha`, predict_tbl$`upr - en_emiss_ha`)) 
# #predict_tbl$mean_synNuse <- rowMeans(cbind(predict_tbl$`lwr - fert_use_ha`, predict_tbl$`upr - fert_use_ha`)) 
# #predict_tbl$mean_synN <- rowMeans(cbind(predict_tbl$`lwr - fert_emiss_ha`, predict_tbl$`upr - fert_emiss_ha`)) 
# #predict_tbl$mean_m <- rowMeans(cbind(predict_tbl$`lwr - m_ha`, predict_tbl$`upr - m_ha`)) 
# 
# #Set upper and lower bounds of standard error error bars
# p_lwr_N <- ((predict_tbl_N$`lwr - p_ha_N` + predict_tbl_N$mean_p)/1.96)
# p_lwr_S <- ((predict_tbl_S$`lwr - p_ha_S` + predict_tbl_S$mean_p)/1.96)
# p_lwr_C <- ((predict_tbl_C$`lwr - p_ha_C` + predict_tbl_C$mean_p)/1.96)
# p_lwr_W <- ((predict_tbl_W$`lwr - p_ha_W` + predict_tbl_W$mean_p)/1.96) 
# p_lwr_E <- ((predict_tbl_E$`lwr - p_ha_e` + predict_tbl_E$mean_p)/1.96)
# 
# p_upr_N <- ((predict_tbl_N$`upr - p_ha_N` + predict_tbl_N$mean_p)/1.96)
# p_upr_S <- ((predict_tbl_S$`upr - p_ha_S` + predict_tbl_S$mean_p)/1.96)
# p_upr_C <- ((predict_tbl_C$`upr - p_ha_C` + predict_tbl_C$mean_p)/1.96)
# p_upr_W <- ((predict_tbl_W$`upr - p_ha_W` + predict_tbl_W$mean_p)/1.96) 
# p_upr_E <- ((predict_tbl_E$`upr - p_ha_e` + predict_tbl_E$mean_p)/1.96)
# 
# f_lwr_N <- ((predict_tbl_N$`lwr - en_emiss_ha_N` + predict_tbl_N$mean_f)/1.96)
# f_lwr_S <- ((predict_tbl_S$`lwr - en_emiss_ha_S` + predict_tbl_S$mean_f)/1.96)
# f_lwr_C <- ((predict_tbl_C$`lwr - en_emiss_ha_C` + predict_tbl_C$mean_f)/1.96)
# f_lwr_W <- ((predict_tbl_W$`lwr - en_emiss_ha_W` + predict_tbl_W$mean_f)/1.96) 
# f_lwr_E <- ((predict_tbl_E$`lwr - en_emiss_ha_e` + predict_tbl_E$mean_f)/1.96)

# f_upr_N <- ((predict_tbl_N$`upr - en_emiss_ha_N`  + predict_tbl_N$mean_f)/1.96)
# f_upr_S <- ((predict_tbl_S$`upr - en_emiss_ha_S` + predict_tbl_S$mean_f)/1.96)
# f_upr_C <- ((predict_tbl_C$`upr - en_emiss_ha_C` + predict_tbl_C$mean_f)/1.96)
# f_upr_W <- ((predict_tbl_W$`upr - en_emiss_ha_W` + predict_tbl_W$mean_f)/1.96)
# f_upr_E <- ((predict_tbl_E$`upr - en_emiss_ha_e` + predict_tbl_E$mean_f)/1.96)
# 
# synNuse_lwr_N <- ((predict_tbl_N$`lwr - synNuse_ha_n` + predict_tbl_N$mean_synNuse)/1.96)
# synNuse_lwr_S <- ((predict_tbl_S$`lwr - synNuse_ha_s` + predict_tbl_S$mean_synNuse)/1.96)
# synNuse_lwr_C <- ((predict_tbl_C$`lwr - synNuse_ha_c` + predict_tbl_C$mean_synNuse)/1.96)
# synNuse_lwr_W <- ((predict_tbl_W$`lwr - syn_Nuse_ha_w` + predict_tbl_W$mean_synNuse)/1.96)
# synNuse_lwr_E <- ((predict_tbl_E$`lwr - syn_Nuse_ha_e` + predict_tbl_E$mean_synNuse)/1.96)
# 
# synNuse_upr_N <- ((predict_tbl_N$`upr - synNuse_ha_n`+ predict_tbl_N$mean_synNuse)/1.96)
# synNuse_upr_S <- ((predict_tbl_S$`upr - synNuse_ha_s` + predict_tbl_S$mean_synNuse)/1.96)
# synNuse_upr_C <- ((predict_tbl_C$`upr - synNuse_ha_c` + predict_tbl_C$mean_synNuse)/1.96)
# synNuse_upr_W <- ((predict_tbl_W$`upr - syn_Nuse_ha_w` + predict_tbl_W$mean_synNuse)/1.96)
# synNuse_upr_E <- ((predict_tbl_E$`upr - syn_Nuse_ha_e` + predict_tbl_E$mean_synNuse)/1.96)
# 
# synN_lwr_N <- ((predict_tbl_N$`lwr - fert_emiss_ha_N` + predict_tbl_N$mean_synN)/1.96)
# synN_lwr_S <- ((predict_tbl_S$`lwr - fert_emiss_ha_S` + predict_tbl_S$mean_synN)/1.96)
# synN_lwr_C <- ((predict_tbl_C$`lwr - fert_emiss_ha_C` + predict_tbl_C$mean_synN)/1.96)
# synN_lwr_W <- ((predict_tbl_W$`lwr - fert_emiss_ha_W` + predict_tbl_W$mean_synN)/1.96)
# synN_lwr_E <- ((predict_tbl_E$`lwr - fert_emiss_ha_E` + predict_tbl_E$mean_synN)/1.96) 
# 
# synN_upr_N <- ((predict_tbl_N$`upr - fert_emiss_ha_N` + predict_tbl_N$mean_synN)/1.96)
# synN_upr_S <- ((predict_tbl_S$`upr - fert_emiss_ha_S` + predict_tbl_S$mean_synN)/1.96)
# synN_upr_C <- ((predict_tbl_C$`upr - fert_emiss_ha_C` + predict_tbl_C$mean_synN)/1.96)
# synN_upr_W <- ((predict_tbl_W$`upr - fert_emiss_ha_W` + predict_tbl_W$mean_synN)/1.96)
# synN_upr_E <- ((predict_tbl_E$`upr - fert_emiss_ha_E` + predict_tbl_E$mean_synN)/1.96)
# 
# m_lwr_N <- ((predict_tbl_N$`lwr - machinery_ha_n` + predict_tbl_N$mean_m)/1.96)
# m_lwr_S <- ((predict_tbl_S$`lwr - machinery_ha_s` + predict_tbl_S$mean_m)/1.96)
# m_lwr_C <- ((predict_tbl_C$`lwr - machinery_ha_c` + predict_tbl_C$mean_m)/1.96)
# m_lwr_W <- ((predict_tbl_W$`lwr - machinery_ha_w` + predict_tbl_W$mean_m)/1.96)
# m_lwr_E <- ((predict_tbl_E$`lwr - machinery_ha_e` + predict_tbl_E$mean_m)/1.96) 
# 
# m_upr_N <- ((predict_tbl_N$`upr - machinery_ha_n` + predict_tbl_N$mean_m)/1.96)
# m_upr_S <- ((predict_tbl_S$`upr - machinery_ha_s` + predict_tbl_S$mean_m)/1.96)
# m_upr_C <- ((predict_tbl_C$`upr - machinery_ha_c` + predict_tbl_C$mean_m)/1.96)
# m_upr_W <- ((predict_tbl_W$`upr - machinery_ha_w` + predict_tbl_W$mean_m)/1.96)
# m_upr_E <- ((predict_tbl_E$`upr - machinery_ha_e` + predict_tbl_E$mean_m)/1.96)

lwr_N <- filter(predict_tbl_N, val_type == "lwr ")
lwr_S <- filter(predict_tbl_S, val_type == "lwr ")
lwr_C <- filter(predict_tbl_C, val_type == "lwr ")
lwr_E <- filter(predict_tbl_E, val_type == "lwr ")
lwr_W <- filter(predict_tbl_W, val_type == "lwr ")
lwr_C$val_type <- NULL
lwr_S$val_type <- NULL
lwr_N$val_type <- NULL
lwr_E$val_type <- NULL
lwr_W$val_type <- NULL

upr_N <- filter(predict_tbl_N, val_type == "upr ")
upr_S <- filter(predict_tbl_S, val_type == "upr ")
upr_C <- filter(predict_tbl_C, val_type == "upr ")
upr_E <- filter(predict_tbl_E, val_type == "upr ")
upr_W <- filter(predict_tbl_W, val_type == "upr ")
upr_C$val_type <- NULL
upr_S$val_type <- NULL
upr_N$val_type <- NULL
upr_E$val_type <- NULL
upr_W$val_type <- NULL

lwr_N <- spread(data = lwr_N, key = Scenario,  value = value )
lwr_S <- spread(data = lwr_S, key = Scenario,  value = value )
lwr_E <- spread(data = lwr_E, key = Scenario,  value = value )
lwr_W <- spread(data = lwr_W, key = Scenario,  value = value )
lwr_C <- spread(data = lwr_C, key = Scenario,  value = value )

upr_N <- spread(data = upr_N, key = Scenario,  value = value )
upr_S <- spread(data = upr_S, key = Scenario,  value = value )
upr_E <- spread(data = upr_E, key = Scenario,  value = value )
upr_W <- spread(data = upr_W, key = Scenario,  value = value )
upr_C <- spread(data = upr_C, key = Scenario,  value = value )

lwr_N <- melt(lwr_N)
lwr_S <- melt(lwr_S)
lwr_C <- melt(lwr_C)
lwr_W <- melt(lwr_W)
lwr_E <- melt(lwr_E)


colnames(lwr_N) <- c("variable", "Scenario", "lwr")
colnames(lwr_S) <- c("variable", "Scenario", "lwr")
colnames(lwr_C) <- c("variable", "Scenario", "lwr")
colnames(lwr_W) <- c("variable", "Scenario", "lwr")
colnames(lwr_E) <- c("variable", "Scenario", "lwr")

upr_N <- melt(upr_N)
upr_S <- melt(upr_S)
upr_C <- melt(upr_C)
upr_W <- melt(upr_W)
upr_E <- melt(upr_E)
colnames(upr_N) <- c("variable", "Scenario", "upr")
colnames(upr_S) <- c("variable", "Scenario", "upr")
colnames(upr_C) <- c("variable", "Scenario", "upr")
colnames(upr_W) <- c("variable", "Scenario", "upr")
colnames(upr_E) <- c("variable", "Scenario", "upr") 

# write.csv(lwr_N,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/lwr_N.csv")
# write.csv(lwr_S,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/lwr_S.csv" )
# write.csv(lwr_C,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/lwr_C.csv" )
# write.csv(lwr_W,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/lwr_W.csv" )
# write.csv(lwr_E,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/lwr_E.csv" )
# 
# write.csv(upr_N,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/upr_N.csv" )
# write.csv(upr_S,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/upr_S.csv" )
# write.csv(upr_C,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/upr_C.csv" )
# write.csv(upr_W,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/upr_W.csv" )
# write.csv(upr_E,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/upr_E.csv" )

```

```{r Save model coeffs for each region}

#write.csv(predict_tbl_C, "~/Desktop/Energy-Ag_tbls/model_coefs_CentralAfr.csv")
#write.csv(predict_tbl_E, "~/Desktop/model_coefs_EastAfr.csv")
#write.csv(predict_tbl_S, "~/Desktop/model_coefs_SouthAfr.csv")
# write.csv(predict_tbl_W, "~/Desktop/model_coefs_WestAfr.csv")
# write.csv(predict_tbl_N, "~/Desktop/model_coefs_NorthAfr.csv")

#save to google drive too
write.csv(predict_tbl_C, "~/Google Drive/My Drive/Food & Farming/Energy in ag/model_coefs_CentralAfr.csv")
write.csv(predict_tbl_E,  "~/Google Drive/My Drive/Food & Farming/Energy in ag/model_coefs_EAfr.csv")
write.csv(predict_tbl_S, "~/Google Drive/My Drive/Food & Farming/Energy in ag/model_coefs_SAfr.csv")
write.csv(predict_tbl_W,  "~/Google Drive/My Drive/Food & Farming/Energy in ag/model_coefs_WAfr.csv")
write.csv(predict_tbl_N, "~/Google Drive/My Drive/Food & Farming/Energy in ag/model_coefs_NAfr.csv")
```


```{r Add LUC data to Energy emissions data}
LUC_Afr_regions <- read.csv("~/Google Drive/My Drive/Food & Farming/Energy in ag/LandDemand/LUC_tot_region_dan2.csv") #bounds by region

#bounds by region #for sensitivity analysis
#Interested in the upper bound of LUC emissions as this represents a less conservative LUC reduction.Can eliminate lower bound estimates where LUC reductions would be higher since cropland is being converted back to native vegetation. The LUC emissions are in kg CO2 equivalents.
#LUC_Afr_regions <- LUC_tot_region for sensitivity analysis

#remove extra columns, demonstrating quicker way to do it. Only include higher LUC emissions, not lower bounds,for a more conservative emissions reduction.
LUC_Afr_regions <- dplyr::select(LUC_Afr_regions, -c(X, High_lwr, Proj_lwr,Base_lwr)) 

LUC_Afr_regions <- as.data.frame(LUC_Afr_regions)

LUC_Afr_regions <- melt(LUC_Afr_regions, id.vars = "Region")
#match dataframe structure of Energy_emis
#LUC_Afr_regions %>% spread(key = Region, value = value) #match dataframe structure of Energy_emis
colnames(LUC_Afr_regions) <- c("Region", "Scenario", "LUC")
LUC_Afr_regions$Scenario <- as.character(LUC_Afr_regions$Scenario)
LUC_Afr_regions$Region <- as.character(LUC_Afr_regions$Region)
LUC_Afr_regions$Scenario[grepl("Base",LUC_Afr_regions$Scenario)] <-"Baseline"
LUC_Afr_regions$Scenario[grepl("Proj",LUC_Afr_regions$Scenario)] <-"Projected"
LUC_Afr_regions$Region[grepl("Northern", LUC_Afr_regions$Region)] <-"North"
LUC_Afr_regions$Scenario[grepl("High_upr",LUC_Afr_regions$Scenario)] <-"High"
 
#Calculate total energy emissions by region and scenario
Energy_emis$variable <- rownames(Energy_emis)
rownames(Energy_emis) <- NULL
B <- filter(Energy_emis, grepl("_base", variable))
P <- filter(Energy_emis, grepl("proj", variable))
H_alt <- filter(Energy_emis, grepl("_h_alt", variable))

Energy_b <- t(colSums(B[, c(1:6)])) #aggregates emissions across all energy sources for each region
rownames(Energy_b) <- "Baseline"
Energy_p <- t(colSums(P[, c(1:6)]))
rownames(Energy_p) <- "Projected"
Energy_h_alt <-  t(colSums(H_alt[, c(1:6)]))
rownames(Energy_h_alt) <- "High"
tot_E <- rbind(Energy_b,Energy_p,Energy_h_alt )
tot_E <- melt(tot_E)
colnames(tot_E) <- c("Scenario", "Region", "Energy")
tot_E$Region<- as.character(tot_E$Region)
tot_E$Region[grepl("Africa",tot_E$Region)] <-"Africa"

#Calculate total GHG
GHG <- right_join(LUC_Afr_regions, tot_E)
GHG[is.na(GHG)] <- 0 #Convert NAs in LUC to 0 (applies to high scenario)
GHG[GHG < 0] <- 0 #convert negative values to 0

#Units - convert from gigagrams to gigatons or megatons
Gg_to_Gt <- 1/1000000 #1 Gigaton/1000000 Gigagrams for converting Energy emissions
GHG$LUC <- (GHG$LUC * kg_to_Gg)/10 #Cropland change was calculated based off 2000 and 2010 data,*also divided by 10 in world carbon loss file 
GHG$LUC <-  (GHG$LUC * Gg_to_Gt)/38 #38 is the number of years between 2012 and 2050, this division annualizes the emissions
GHG$Energy <- GHG$Energy * Gg_to_Gt
GHG$GHG <- GHG$LUC + GHG$Energy
write.csv(GHG,"~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/GHG_emis.csv")


```

```{r Plot GHG data across Africa's regions and for SSA as a whole}

GHG_Afr <- GHG[GHG$Region == "Africa",] #have separate charts for SSA data to compare to region breakdown
GHG <- anti_join(GHG, GHG_Afr)
#GHG_high <- GHG[GHG$Scenario == "High",] #Use High_alt as High
#GHG <- anti_join(GHG,GHG_high)
GHG$Scenario <- factor(GHG$Scenario ,levels = c("Baseline", "Projected", "High_alt")) #Change order of bars so it is not in alphabetical order, but rather in the order of the yield-scenarios
x.axis <- c("Baseline", "Projected", "High")

#use BTI style guide for charts
#set up
library(tidyverse); library(grid); 
#library(RCurl)

#set fonts 
load_font <- function() {
  text_font <<-  "Manuale"
  title_font <<- "Futura"
  print("Note: Download Futura.ttc and Manuale-Regular.ttf fonts first. Default location should be Library/Fonts/ folder. Url: https://www.dropbox.com/work/Style%20Guide/BTI%20Letterhead/Letterhead%20Font")
  library(sysfonts) 
  library(showtext)
  sysfonts::font_add(family="Futura", regular = "~/Library/Fonts/Futura.ttc")  #~/../../System/Library/Fonts/Supplemental/Futura.ttc")   #ttf: futura-regular.ttf
  sysfonts::font_add(family="Manuale", regular = "~/Library/Fonts/manuale-regular.ttf")
  showtext_auto()
}

bti_colors <- c("#0d4459", "#00a990", "#d05527", "#a33332",
                "#b381d0",  "#dfb9a6", "#b2b2b1", "#2A2A2A", "#ecc627")
#general plot theme
theme_bti <- function (base_size = 14, base_family = "Helvetica") {
  theme_classic() %+replace% 
    theme(plot.title = element_text(color = "black",  size = 14), 
          strip.text.x = element_text(size = 14),
          strip.background = element_blank(),
          
          #gridlines
          panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank(), #no grid lines
          panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), #no grid lines
          #background and border
          panel.border = element_blank(), #no plot border
          #panel.background = element_rect(fill = "white"), #white panel background 
          #legend
          legend.position = "bottom", #legend default position is bottom
          legend.key = element_rect(fill = "#FFFFFF00", color = NA), #no border around legend items
          legend.text = element_text(size=10),
          legend.title = element_text(size=10),
          #axes
          axis.line.x = element_line(color="black", size = .5),
          axis.line.y = element_line(color="black", size = .5),
          axis.title.y = element_text(size = 12, angle = 90), 
          axis.title.x = element_text(size = 12), 
          #logo 
          plot.margin = unit(c(0.5, 0.5, 2, 0.5), "lines") # add space for logo
    )
}

#percent stacked bar chart by region
GHG$Region <- factor(GHG$Region, levels = c("West", "East", "Southern", "Central", "North"))
GHG$Scenario <- factor(GHG$Scenario ,levels = c("Baseline", "Projected", "High"))
GHG_region <- ggplot(GHG, aes(fill= Region, y= GHG, x= Scenario)) + 
    geom_bar(position="fill", stat="identity") + ggtitle(expression(paste("% Greenhouse emissions by region in Africa for each scenario"))) + xlab("Scenarios") + ylab("% of each scenario's GHG emissions") + labs(fill = "Regions")  + scale_x_discrete(labels= x.axis) +  theme(axis.title.x = element_text(color="black",size=12),axis.title.y = element_text(color="black", size=12) ,panel.background = element_rect(fill = NA),
       panel.grid.major.y = element_line(colour="grey68",linetype="solid"),
       panel.grid.major.x = element_line(colour="grey68",linetype="solid"),axis.ticks.y = element_blank(),axis.ticks.x=element_blank(),
       plot.title = element_text(size=15, face="bold")) 
      # plot.background = element_rect(fill=NA), legend.key=element_rect(fill=NA)
GHG_region <- GHG_region  +  scale_fill_manual(values=wes_palette(n=5, name="Darjeeling1")) 
GHG_region
ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/GHG_region.png", GHG_region) #save ggplot, not great with dimensions, might use current plot window as default plot size and so may need to specify width and height, dims: Saving 7.29 x 4.51 in image


#bar chart by region, grouped

GHG$Region <- factor(GHG$Region, levels = c("West", "East", "Southern", "Central", "North"))
GHG_region_grouped <- ggplot(GHG, aes(fill= Region, y= GHG, x= Scenario)) + 
    geom_bar(position="dodge", stat="identity") + ggtitle(expression(paste("Greenhouse emissions by scenario and region in Africa"))) + xlab("Scenarios") + ylab("GHG Emissions (Gigagtons CO2eq)") + labs(fill = "Regions")  + scale_x_discrete(labels= x.axis) +  theme_bti()

GHG_region_grouped <- GHG_region_grouped  +  scale_fill_manual(values=bti_colors) 
ggsave(filename =  "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/GHG_region_grouped.png", plot = GHG_region_grouped )
GHG_region_grouped

#Stacked
GHG_region_stacked <- ggplot(GHG, aes(fill= Region, y= GHG, x= Scenario)) + 
    geom_bar(position="stack", stat="identity") + ggtitle(expression(paste("Greenhouse emissions by scenario for each region in Africa"))) + xlab("Scenarios") + ylab("GHG emissions (Gt CO2eq)") + labs(fill = "African regions")  + scale_x_discrete(labels= x.axis) +  theme(axis.title.x = element_text(color="black",size=12),axis.title.y = element_text(color="black", size=12) ,panel.background = element_rect(fill = NA),
       panel.grid.major.y = element_line(colour="grey68",linetype="solid"),
       panel.grid.major.x = element_line(colour="grey68",linetype="solid"),axis.ticks.y = element_blank(),axis.ticks.x=element_blank(),
       plot.title = element_text(size=15, face="bold")) 
      # plot.background = element_rect(fill=NA), legend.key=element_rect(fill=NA)
GHG_region_stacked <- GHG_region  +  scale_fill_manual(values=bti_colors) 
ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/GHG_region_stacked.png", plot = GHG_region_stacked, width = , height = )

# Africa
#GHG_Afr_high <- GHG_SSA[GHG_Afr$Scenario == "High",] #Use High_alt as High
#GHG_Afr <- anti_join(GHG_Afr,GHG_SSA_high)
GHG_Afr$Scenario <- factor(GHG_Afr$Scenario ,levels = c("Baseline", "Projected", "High_alt"))

GHG_Afr_plot <- ggplot(GHG_Afr, aes(y = GHG, x= Scenario)) + 
    geom_bar(position= "stack", stat="identity",fill = "#0DC3A8") + ggtitle(expression(paste("Greenhouse emissions by scenario in Africa"))) + xlab("Scenarios") + ylab("GHG Emissions (Gigatons CO2eq)") + labs(fill = "African regions")  + scale_x_discrete(labels= x.axis) +  theme(axis.title.x = element_text(color="black",size=12),axis.title.y = element_text(color="black", size=12) ,panel.background = element_rect(fill = NA),
       panel.grid.major.y = element_line(colour="grey68",linetype="solid"),
       panel.grid.major.x = element_line(colour="grey68",linetype="solid"),axis.ticks.y = element_blank(),axis.ticks.x=element_blank(),
       plot.title = element_text(size=15, face="bold"))
 ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/GHG_Afr.png", plot = GHG_Afr_plot )   


```

```{r Energy emissions by region }
#Melt data for ggplot
Energy_emis <- melt(Energy_emis)
colnames(Energy_emis) <- c("Energy_Scenario", "Region", "Value")
Energy_emis$Value <- Energy_emis$Value * Gg_to_Gt


#separate scenario from energy source into 2 columns
Energy_emis$Energy_Scenario <- str_replace(Energy_emis$Energy_Scenario, "synN_use", "synNuse") ##change "syn_use_" to synuse to make it easier to separate values into 2 cols
Energy_emis$Energy_Scenario <- str_replace(Energy_emis$Energy_Scenario, "h_alt", "alt")
Energy_emis <- Energy_emis %>% separate(Energy_Scenario, c("Energy Source", "Scenario"), "_")

#Change naming conventions to match that of error bars to making joining easier
Energy_emis$`Energy Source` <- str_replace(Energy_emis$`Energy Source`, "synNuse","Manufacturing Fertilizers")
Energy_emis$`Energy Source` <- str_replace(Energy_emis$`Energy Source`, "pest","Manufacturing Pesticides")
Energy_emis$`Energy Source` <- str_replace(Energy_emis$`Energy Source`, "m","Embodied Energy in Machinery")
Energy_emis$`Energy Source` <- str_replace(Energy_emis$`Energy Source`, "synN","Synthetic N")
Energy_emis$`Energy Source` <- str_replace(Energy_emis$`Energy Source`, "fuel","On-Farm Fuel")

Energy_emis$Scenario <- str_replace(Energy_emis$Scenario, "base","Baseline")
Energy_emis$Scenario <- str_replace(Energy_emis$Scenario, "proj","Projected")
Energy_emis$Scenario <- str_replace(Energy_emis$Scenario, "alt","High")

#Split data by region
Energy_emis_E<- filter(Energy_emis, Region == "East")
Energy_emis_W <- filter(Energy_emis, Region == "West")
Energy_emis_S <- filter(Energy_emis, Region == "Southern")
Energy_emis_C <- filter(Energy_emis, Region == "Central")
Energy_emis_N <- filter(Energy_emis, Region == "North")
Energy_emis_Afr <- filter(Energy_emis, Region == "Africa")
Energy_emis_N$Region <- NULL
Energy_emis_S$Region <- NULL
Energy_emis_W$Region <- NULL
Energy_emis_E$Region <- NULL
Energy_emis_C$Region <- NULL
Energy_emis_Afr$Region <- NULL


```


```{r Energy emissions charts by region }
#Add in upper and lower error bars data for each region and multiply by cropland, emissions & conversions factors if necessary 

#North Africa
colnames(lwr_N) <- c("Energy Source", "Scenario", "lwr")
colnames(upr_N) <- c("Energy Source", "Scenario", "upr")
lwr_N$`Energy Source`<- trimws(lwr_N$`Energy Source`) #eliminate extra spaces in energy source strings
upr_N$`Energy Source`<- trimws(upr_N$`Energy Source`) #eliminate extra spaces in energy source strings
lwr_N$Scenario <- str_replace(lwr_N$Scenario, "High_alt", "High")
upr_N$Scenario <- str_replace(upr_N$Scenario, "High_alt", "High")
lwr_N$Scenario <- as.character(lwr_N$Scenario)
upr_N$Scenario <- as.character(upr_N$Scenario)

#join upper and lower 95% CI values from the model with the estimates of energy emissions by source
Energy_emis_N <- right_join(Energy_emis_N, lwr_N, by = c("Energy Source", "Scenario"))
Energy_emis_N <- right_join(Energy_emis_N, upr_N, by = c("Energy Source", "Scenario"))

#Multiply 95% CI estimates by cropland  
Energy_emis_N$cropland[Energy_emis_N$Scenario == "Baseline"] <- area_b$harv_area[area_b$region == "North"]
Energy_emis_N$cropland[Energy_emis_N$Scenario == "Projected"] <-  area_p$harv_area[area_p$region == "North"]
Energy_emis_N$cropland[Energy_emis_N$Scenario == "High"] <-  area_h_alt$harv_area[area_h_alt$region == "North"]
#Converts upper and lower estimates are in Gigagrams or tons (manufacturing pesticides is in tons)
Energy_emis_N$lwr <- Energy_emis_N$lwr * Energy_emis_N$cropland  
Energy_emis_N$upr <- Energy_emis_N$upr * Energy_emis_N$cropland 

Energy_emis_N$lwr[Energy_emis_N$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_N$lwr[Energy_emis_N$`Energy Source` == "Manufacturing Fertilizers"] * fert_ef  * kg_to_Gg
Energy_emis_N$lwr[Energy_emis_N$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_N$lwr[Energy_emis_N$`Energy Source` == "Manufacturing Pesticides"] * pest_ef  * tons_to_Gg
Energy_emis_N$upr[Energy_emis_N$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_N$upr[Energy_emis_N$`Energy Source` == "Manufacturing Fertilizers"] * fert_ef  * kg_to_Gg
Energy_emis_N$upr[Energy_emis_N$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_N$upr[Energy_emis_N$`Energy Source` == "Manufacturing Pesticides"] * pest_ef  * tons_to_Gg

#Convert all lower and upper estimates to Gigatons to match the units of the fitted values
Energy_emis_N$lwr <- Energy_emis_N$lwr * Gg_to_Gt
Energy_emis_N$upr <- Energy_emis_N$upr * Gg_to_Gt


#southern Africa
colnames(lwr_S) <- c("Energy Source", "Scenario", "lwr")
colnames(upr_S) <- c("Energy Source", "Scenario", "upr")
lwr_S$`Energy Source` <- trimws(lwr_S$`Energy Source`)
upr_S$`Energy Source` <- trimws(upr_S$`Energy Source`)
lwr_S$Scenario <- str_replace(lwr_S$Scenario , "High_alt", "High")
upr_S$Scenario <- str_replace(upr_S$Scenario , "High_alt", "High")
Energy_emis_S <- right_join(Energy_emis_S, lwr_S, by = c("Energy Source", "Scenario"))
Energy_emis_S <- right_join(Energy_emis_S, upr_S, by = c("Energy Source", "Scenario"))


#Multiply 95% CI estimates by cropland  
Energy_emis_S$cropland[Energy_emis_S$Scenario == "Baseline"] <- area_b$harv_area[area_b$region == "South"]
Energy_emis_S$cropland[Energy_emis_S$Scenario == "Projected"] <-  area_p$harv_area[area_p$region == "South"]
Energy_emis_S$cropland[Energy_emis_S$Scenario == "High"] <-  area_h_alt$harv_area[area_h_alt$region == "South"]
Energy_emis_S$lwr <- Energy_emis_S$lwr * Energy_emis_S$cropland
Energy_emis_S$upr <- Energy_emis_S$upr * Energy_emis_S$cropland

Energy_emis_S$lwr[Energy_emis_S$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_S$lwr[Energy_emis_S$`Energy Source` == "Manufacturing Fertilizers"]  * fert_ef * kg_to_Gg
Energy_emis_S$lwr[Energy_emis_S$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_S$lwr[Energy_emis_S$`Energy Source` == "Manufacturing Pesticides"] * pest_ef * tons_to_Gg 
Energy_emis_S$upr[Energy_emis_S$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_S$upr[Energy_emis_S$`Energy Source` == "Manufacturing Fertilizers"]  * fert_ef * kg_to_Gg 
Energy_emis_S$upr[Energy_emis_S$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_S$upr[Energy_emis_S$`Energy Source` == "Manufacturing Pesticides"] * pest_ef * tons_to_Gg 

#Convert all lower and upper estimates to Gigatons to match the units of the fitted values
Energy_emis_S$lwr <- Energy_emis_S$lwr * Gg_to_Gt
Energy_emis_S$upr <- Energy_emis_S$upr * Gg_to_Gt

#west Africa
colnames(lwr_W) <- c("Energy Source", "Scenario", "lwr")
colnames(upr_W) <- c("Energy Source", "Scenario", "upr")
lwr_W$`Energy Source` <- trimws(lwr_W$`Energy Source`)
upr_W$`Energy Source` <- trimws(upr_W$`Energy Source`)
lwr_W$Scenario <- str_replace(lwr_W$Scenario , "High_alt", "High")
upr_W$Scenario <- str_replace(upr_W$Scenario , "High_alt", "High")
Energy_emis_W <- right_join(Energy_emis_W, lwr_W, by = c("Energy Source", "Scenario"))
Energy_emis_W <- right_join(Energy_emis_W, upr_W, by = c("Energy Source", "Scenario"))

#Add in lower and upper 95% CI estimates and multiply by cropland to get gigagrams or tons (manufacturing energy sources)
Energy_emis_W$cropland[Energy_emis_W$Scenario == "Baseline"] <- area_b$harv_area[area_b$region == "West"]
Energy_emis_W$cropland[Energy_emis_W$Scenario == "Projected"] <-  area_p$harv_area[area_p$region == "West"]
Energy_emis_W$cropland[Energy_emis_W$Scenario == "High"] <-  area_h_alt$harv_area[area_h_alt$region == "West"]
Energy_emis_W$lwr <- Energy_emis_W$lwr * Energy_emis_W$cropland 
Energy_emis_W$upr <- Energy_emis_W$upr * Energy_emis_W$cropland

#Convert manufacturing fert and pest to Gg 
Energy_emis_W$lwr[Energy_emis_W$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_W$lwr[Energy_emis_W$`Energy Source` == "Manufacturing Fertilizers"] * fert_ef * kg_to_Gg 
Energy_emis_W$lwr[Energy_emis_W$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_W$lwr[Energy_emis_W$`Energy Source` == "Manufacturing Pesticides"] * pest_ef * tons_to_Gg
Energy_emis_W$upr[Energy_emis_W$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_W$upr[Energy_emis_W$`Energy Source` == "Manufacturing Fertilizers"] * fert_ef * kg_to_Gg
Energy_emis_W$upr[Energy_emis_W$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_W$upr[Energy_emis_W$`Energy Source` == "Manufacturing Pesticides"] * pest_ef * tons_to_Gg 

#Convert all lower and upper estimates to Gigatons to match the units of the fitted values
Energy_emis_W$lwr <- Energy_emis_W$lwr * Gg_to_Gt
Energy_emis_W$upr <- Energy_emis_W$upr * Gg_to_Gt

#east Africa
colnames(lwr_E) <- c("Energy Source", "Scenario", "lwr")
colnames(upr_E) <- c("Energy Source", "Scenario", "upr")
lwr_E$`Energy Source` <- trimws(upr_E$`Energy Source`)
upr_E$`Energy Source` <- trimws(lwr_E$`Energy Source`)
lwr_E$Scenario <- str_replace(lwr_E$Scenario , "High_alt", "High")
upr_E$Scenario <- str_replace(upr_E$Scenario , "High_alt", "High")
Energy_emis_E <- right_join(Energy_emis_E, lwr_E, by = c("Energy Source", "Scenario"))
Energy_emis_E <- right_join(Energy_emis_E, upr_E, by = c("Energy Source", "Scenario"))

#Multiply lower and upper 95% by cropland 
Energy_emis_E$cropland[Energy_emis_E$Scenario == "Baseline"] <- area_b$harv_area[area_b$region == "East"]
Energy_emis_E$cropland[Energy_emis_E$Scenario == "Projected"] <-  area_p$harv_area[area_p$region == "East"]
Energy_emis_E$cropland[Energy_emis_E$Scenario == "High"] <-  area_h_alt$harv_area[area_h_alt$region == "East"]

#Converts upper and lower estimates are in Gigagrams or tons (manufacturing pesticides/fertilizers is in tons)
Energy_emis_E$lwr <- Energy_emis_E$lwr * Energy_emis_E$cropland  
Energy_emis_E$upr <- Energy_emis_E$upr * Energy_emis_E$cropland 

#convert upper and lower estimates to gigagrams for manufacturing emissions
Energy_emis_E$lwr[Energy_emis_E$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_E$lwr[Energy_emis_E$`Energy Source` == "Manufacturing Fertilizers"] * fert_ef * kg_to_Gg
Energy_emis_E$lwr[Energy_emis_E$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_E$lwr[Energy_emis_E$`Energy Source` == "Manufacturing Pesticides"] * pest_ef * tons_to_Gg #Did not multiply by pest_ef 
Energy_emis_E$upr[Energy_emis_E$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_E$upr[Energy_emis_E$`Energy Source` == "Manufacturing Fertilizers"] * fert_ef * kg_to_Gg
Energy_emis_E$upr[Energy_emis_E$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_E$upr[Energy_emis_E$`Energy Source` == "Manufacturing Pesticides"] * pest_ef *  tons_to_Gg

#Convert all lower and upper estimates to Gigatons to match the units of the fitted values
Energy_emis_E$lwr <- Energy_emis_E$lwr * Gg_to_Gt
Energy_emis_E$upr <- Energy_emis_E$upr * Gg_to_Gt

#Central Africa
colnames(lwr_C) <- c("Energy Source", "Scenario", "lwr")
colnames(upr_C) <- c("Energy Source", "Scenario", "upr")
lwr_C$`Energy Source` <- trimws(lwr_C$`Energy Source`)
upr_C$`Energy Source` <- trimws(lwr_C$`Energy Source`)
lwr_C$Scenario <- str_replace(lwr_C$Scenario , "High_alt", "High")
upr_C$Scenario <- str_replace(upr_C$Scenario , "High_alt", "High")
Energy_emis_C <- right_join(Energy_emis_C, lwr_C, by = c("Energy Source", "Scenario"))
Energy_emis_C <- right_join(Energy_emis_C, upr_C, by = c("Energy Source", "Scenario"))

Energy_emis_C$cropland[Energy_emis_C$Scenario == "Baseline"] <- area_b$harv_area[area_b$region == "Central"]
Energy_emis_C$cropland[Energy_emis_C$Scenario == "Projected"] <-  area_p$harv_area[area_p$region == "Central"]
Energy_emis_C$cropland[Energy_emis_C$Scenario == "High"] <-  area_h_alt$harv_area[area_h_alt$region == "Central"]
#Converts upper and lower estimates are in Gigagrams or tons (manufacturing pesticides/fertilizers is in tons)
Energy_emis_C$lwr <- Energy_emis_C$lwr * Energy_emis_C$cropland  
Energy_emis_C$upr <- Energy_emis_C$upr * Energy_emis_C$cropland 

#convert upper and lower estimates to gigagrams for manufacturing emissions
Energy_emis_C$lwr[Energy_emis_C$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_C$lwr[Energy_emis_C$`Energy Source` == "Manufacturing Fertilizers"] * fert_ef * kg_to_Gg 
Energy_emis_C$lwr[Energy_emis_C$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_C$lwr[Energy_emis_C$`Energy Source` == "Manufacturing Pesticides"] * pest_ef * tons_to_Gg #Did not multiply by pest_ef 
Energy_emis_C$upr[Energy_emis_C$`Energy Source` == "Manufacturing Fertilizers"] <- Energy_emis_C$upr[Energy_emis_C$`Energy Source` == "Manufacturing Fertilizers"] * fert_ef * kg_to_Gg
Energy_emis_C$upr[Energy_emis_C$`Energy Source` == "Manufacturing Pesticides"] <- Energy_emis_C$upr[Energy_emis_C$`Energy Source` == "Manufacturing Pesticides"] * pest_ef *  tons_to_Gg

#Convert all lower and upper estimates to Gigatons to match the units of the fitted values
Energy_emis_C$lwr <- Energy_emis_C$lwr * Gg_to_Gt
Energy_emis_C$upr <- Energy_emis_C$upr * Gg_to_Gt

#Calculate lwr and upr error bounds for Africa
# Energy_emis_E$Scenario <- as.matrix(unlist(Energy_emis_E$Scenario))
# Energy_emis_E$Scenario[is.na(Energy_emis_E$Scenario)] <- "High"
Energy_emis_Afr$MoE <- (Energy_emis_C$Value - Energy_emis_C$lwr)^2 + (Energy_emis_N$Value - Energy_emis_N$lwr)^2 +  (Energy_emis_S$Value - Energy_emis_S$lwr)^2 +  (Energy_emis_W$Value - Energy_emis_W$lwr)^2
                                                                                                                        
Energy_emis_Afr$sqrt_MoE <- sqrt(Energy_emis_Afr$MoE)
Energy_emis_Afr$upr <- Energy_emis_Afr$Value + Energy_emis_Afr$sqrt_MoE
Energy_emis_Afr$lwr <- Energy_emis_Afr$Value - Energy_emis_Afr$sqrt_MoE

#rename inputs

#syn n application
Energy_emis_E$`Energy Source` <- str_replace(Energy_emis_E$`Energy Source` , "Synthetic N", "Synthetic N Application")
Energy_emis_W$`Energy Source` <- str_replace(Energy_emis_W$`Energy Source` , "Synthetic N", "Synthetic N Application")
Energy_emis_S$`Energy Source` <- str_replace(Energy_emis_S$`Energy Source` , "Synthetic N", "Synthetic N Application")
Energy_emis_N$`Energy Source` <- str_replace(Energy_emis_N$`Energy Source` , "Synthetic N", "Synthetic N Application")
Energy_emis_C$`Energy Source` <- str_replace(Energy_emis_C$`Energy Source` , "Synthetic N", "Synthetic N Application")
Energy_emis_Afr$`Energy Source` <- str_replace(Energy_emis_Afr$`Energy Source` , "Synthetic N", "Synthetic N Application")

#fert manufacturing
Energy_emis_E$`Energy Source` <- str_replace(Energy_emis_E$`Energy Source` , "Manufacturing Fertilizers", "Manufacturing Synthetic N Fertilizer")
Energy_emis_W$`Energy Source` <- str_replace(Energy_emis_W$`Energy Source` , "Manufacturing Fertilizers", "Manufacturing Synthetic N Fertilizer")
Energy_emis_S$`Energy Source` <- str_replace(Energy_emis_S$`Energy Source` , "Manufacturing Fertilizers", "Manufacturing Synthetic N Fertilizer")
Energy_emis_N$`Energy Source` <- str_replace(Energy_emis_N$`Energy Source` , "Manufacturing Fertilizers", "Manufacturing Synthetic N Fertilizer")
Energy_emis_C$`Energy Source` <- str_replace(Energy_emis_C$`Energy Source` , "Manufacturing Fertilizers", "Manufacturing Synthetic N Fertilizer")
Energy_emis_Afr$`Energy Source` <- str_replace(Energy_emis_Afr$`Energy Source` , "Manufacturing Fertilizers", "Manufacturing Synthetic N Fertilizer")

#machinery
Energy_emis_E$`Energy Source` <- str_replace(Energy_emis_E$`Energy Source` , "Embodied Energy in Machinery", "Manufacturing Machinery")
Energy_emis_W$`Energy Source` <- str_replace(Energy_emis_W$`Energy Source` , "Embodied Energy in Machinery", "Manufacturing Machinery")
Energy_emis_S$`Energy Source` <- str_replace(Energy_emis_S$`Energy Source` , "Embodied Energy in Machinery", "Manufacturing Machinery")
Energy_emis_N$`Energy Source` <- str_replace(Energy_emis_N$`Energy Source` , "Embodied Energy in Machinery", "Manufacturing Machinery")
Energy_emis_C$`Energy Source` <- str_replace(Energy_emis_C$`Energy Source` , "Embodied Energy in Machinery", "Manufacturing Machinery")
Energy_emis_Afr$`Energy Source` <- str_replace(Energy_emis_Afr$`Energy Source` , "Embodied Energy in Machinery", "Manufacturing Machinery")

#change y-axis to megatons and upper and lower error bars
Gt_Mt <- 1000
Energy_emis_E$Value <- Energy_emis_E$Value * Gt_Mt
Energy_emis_W$Value <- Energy_emis_W$Value * Gt_Mt
Energy_emis_S$Value <- Energy_emis_S$Value * Gt_Mt
Energy_emis_C$Value <- Energy_emis_C$Value * Gt_Mt
Energy_emis_N$Value <- Energy_emis_N$Value * Gt_Mt
Energy_emis_Afr$Value <- Energy_emis_Afr$Value * Gt_Mt

#lwr
Energy_emis_E$lwr <- Energy_emis_E$lwr * Gt_Mt
Energy_emis_W$lwr <- Energy_emis_W$lwr * Gt_Mt
Energy_emis_S$lwr <- Energy_emis_S$lwr * Gt_Mt
Energy_emis_C$lwr <- Energy_emis_C$lwr * Gt_Mt
Energy_emis_N$lwr <- Energy_emis_N$lwr * Gt_Mt
Energy_emis_Afr$lwr <- Energy_emis_Afr$lwr * Gt_Mt

#upr
Energy_emis_E$upr <- Energy_emis_E$upr * Gt_Mt
Energy_emis_W$upr <- Energy_emis_W$upr * Gt_Mt
Energy_emis_S$upr <- Energy_emis_S$upr * Gt_Mt
Energy_emis_C$upr <- Energy_emis_C$upr * Gt_Mt
Energy_emis_N$upr <- Energy_emis_N$upr * Gt_Mt
Energy_emis_Afr$upr <- Energy_emis_Afr$upr * Gt_Mt

#Energy graphs by region
#Energy_E_high <- Energy_emis_E[Energy_emis_E$Scenario == "High_alt",] #Use High_alt as High
#Energy_emis_E<- anti_join(Energy_emis_E, Energy_E_high)
Energy_emis_E$Scenario <- factor(Energy_emis_E$Scenario ,levels = c("Baseline", "Projected", "High"))

Energy_E <- ggplot(Energy_emis_E, aes(fill = `Energy Source` , y = Value, x = Scenario)) + 
    geom_bar(position="dodge", stat="identity" ) + ggtitle(expression(paste("East"))) + xlab("Scenario") + ylab("GHG Emissions (Gt CO2 eq)") + labs(fill = "Inputs") + geom_errorbar(aes(ymin = lwr, ymax= upr), width=.2,
                 position=position_dodge(.9))  +  scale_x_discrete(labels= x.axis) +   scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) + theme_bti()
Energy_E <- Energy_E  +  scale_fill_manual(values=bti_colors)
ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/Energy_E.png", plot = Energy_E)  

#West Africa
Energy_emis_W$Scenario <- factor(Energy_emis_W$Scenario ,levels = c("Baseline", "Projected", "High"))

Energy_W <- ggplot(Energy_emis_W, aes(fill = `Energy Source` , y = Value, x = Scenario)) + 
    geom_bar(position="dodge", stat="identity" ) + ggtitle(expression(paste("West"))) + xlab("Scenario") + ylab("GHG Emissions (Gt CO2eq)") + labs(fill = "Inputs") + geom_errorbar(aes(ymin= lwr , ymax= upr), width=0.2,
                 position=position_dodge(.9))  +  scale_x_discrete(labels= x.axis) +   scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1)))  + theme_bti()
Energy_W <- Energy_W  +  scale_fill_manual(values=bti_colors)
ggsave(filename ="~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/Energy_W.png", plot = Energy_W)  

#Central Africa
Energy_emis_C$Scenario <- factor(Energy_emis_C$Scenario ,levels = c("Baseline", "Projected", "High"))

Energy_C <- ggplot(Energy_emis_C, aes(fill = `Energy Source` , y = Value, x = Scenario)) + 
    geom_bar(position="dodge", stat="identity" ) + ggtitle(expression(paste("Central"))) + xlab("Scenario") + ylab("GHG Emissions (Gt CO2eq)") + labs(fill = "Inputs") + geom_errorbar(aes(ymin= lwr , ymax= upr), width=.2,
                 position=position_dodge(.9))  +  scale_x_discrete(labels= x.axis) +   scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) + theme_bti()
Energy_C <- Energy_C  +  scale_fill_manual(values=bti_colors)
ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/Energy_C.png", plot = Energy_C )  

#Southern Africa
Energy_emis_S$Scenario <- factor(Energy_emis_S$Scenario ,levels = c("Baseline", "Projected", "High"))

Energy_S <- ggplot(Energy_emis_S, aes(fill = `Energy Source` , y = Value, x = Scenario)) + 
    geom_bar(position="dodge", stat="identity" ) + ggtitle(expression(paste("Southern"))) + xlab("Scenario") + ylab("GHG Emissions (Gt CO2eq)") + labs(fill = "Inputs") + geom_errorbar(aes(ymin= lwr , ymax= upr), width=.2,
                 position=position_dodge(.9))  +  scale_x_discrete(labels= x.axis) +   scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) + theme_bti()
Energy_S <- Energy_S  +  scale_fill_manual(values= bti_colors)
ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/Energy_S.png", plot = Energy_S, width = , height = )  


#North Africa
Energy_emis_N$Scenario <- factor(Energy_emis_N$Scenario ,levels = c("Baseline", "Projected", "High"))

Energy_N <- ggplot(Energy_emis_N, aes(fill = `Energy Source` , y = Value, x = Scenario))  +  geom_bar(position="dodge", stat="identity" ) + ggtitle(expression(paste("North")))  + xlab("Scenario") + ylab("GHG Emissions (Gt CO2eq)") + labs(fill = "Inputs") + geom_errorbar(aes(ymin= lwr , ymax= upr), width=.2,
                 position=position_dodge(.9))  +  scale_x_discrete(labels= x.axis) +  scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) + theme_bti()
Energy_N <- Energy_N  +  scale_fill_manual(values= bti_colors)
ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/Energy_N.png", plot = Energy_N)  

#Africa
Energy_emis_Afr$Scenario <- factor(Energy_emis_Afr$Scenario ,levels = c("Baseline", "Projected", "High"))

Energy_Afr <- ggplot(Energy_emis_Afr, aes(fill = `Energy Source` , y = Value, x = Scenario))  +  geom_bar(position="dodge", stat="identity" ) + ggtitle(expression(paste("Africa")))  + xlab("Scenario") + ylab("GHG Emissions (Gt CO2eq)") + labs(fill = "Inputs") + geom_errorbar(aes(ymin= lwr , ymax= upr), width=.2,
                 position=position_dodge(.9))  +  scale_x_discrete(labels= x.axis) + scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) + theme_bti()
Energy_Afr <- Energy_Afr  +  scale_fill_manual(values= bti_colors)
ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/Energy_N.png", plot = Energy_Afr) 


#total Energy graphs with all regions included except SSA (no error bars)
Energy_emis_all <- Energy_emis %>% group_by(Scenario, Region) %>% summarize(sum(Value)) 
Energy_emis_Afr_all <- Energy_emis_all[Energy_emis_all$Region == "Africa",]
Energy_emis_all <- anti_join(Energy_emis_all,Energy_emis_Afr_all )
Energy_emis_all$Scenario <- factor(Energy_emis_all$Scenario ,levels = c("Baseline", "Projected", "High"))

Energy_emis_all_reg <- ggplot(Energy_emis_all, aes(fill = Region , y = `sum(Value)`, x = Scenario)) + 
    geom_bar(position="dodge", stat="identity" ) + ggtitle(expression(paste("Energy Input Use Emissions by Region"))) + xlab("Scenario") + ylab("GHG Emissions (Gt CO2eq)") + labs(fill = "Region") + theme_bti()
Energy_emis_all_reg <- Energy_emis_all_reg +  scale_fill_manual(values= bti_colors)
ggsave(filename = "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/Energy_all_reg.png", plot = Energy_emis_all_reg, width = , height = )

#Create a figure that has all of the energy source by region grafs displayed
Energy_N <- Energy_N + ggtitle("") + ylab("") + xlab("") +  theme_bti() 
Energy_S <- Energy_S + ggtitle("") + ylab("") + xlab("") + theme_bti() 
Energy_W <- Energy_W + ggtitle("") + ylab("") + xlab("") +  theme_bti() 
Energy_E <- Energy_E + ggtitle("") + ylab("") + xlab("") + theme_bti()  
Energy_C <- Energy_C + ggtitle("") + ylab("") + xlab("") +  theme_bti() 
Energy_Afr <-  Energy_Afr + ggtitle("") + ylab("") + xlab("") + theme_bti()  

library(ggpubr)
energy_region_grafs <- ggarrange(Energy_N, Energy_S, Energy_W, Energy_E, Energy_C, Energy_Afr, labels = c("North", "Southern","West","East", "Central", "Africa"),font.label = list(size = 12, face = "plain", color = "black", family = NULL), common.legend = TRUE, legend = "bottom")


# Annotate the figure by adding a common labels
energy_region_grafs <- annotate_figure(energy_region_grafs,
                top = text_grob("Emissions from Input Use by Region", color = "black" , size = 12),
                left = text_grob("GHG Emissions (Mt CO2eq)", color = "black", rot = 90))
                
                #fig.lab = "Figure 1", fig.lab.face = "bold")
ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/panel_energy_reg_grafs.png", plot = energy_region_grafs, width = , height = )


#Total Energy emissions error bars, and with LUC emis for each region 

#add in lwr and upr bounds for Energy emissions
Energy_emis_E$MoE <- Energy_emis_E$Value - Energy_emis_E$lwr
Energy_emis_C$MoE <- Energy_emis_C$Value - Energy_emis_C$lwr
Energy_emis_S$MoE <- Energy_emis_S$Value - Energy_emis_S$lwr
Energy_emis_N$MoE <- Energy_emis_N$Value - Energy_emis_N$lwr
Energy_emis_W$MoE <- Energy_emis_W$Value - Energy_emis_W$lwr

Energy_emis_E$MoE2 <- Energy_emis_E$MoE^2
Energy_emis_C$MoE2 <- Energy_emis_C$MoE^2
Energy_emis_W$MoE2 <- Energy_emis_W$MoE^2
Energy_emis_N$MoE2 <- Energy_emis_N$MoE^2
Energy_emis_W$MoE2 <- Energy_emis_W$MoE^2

# En <- as.data.frame(matrix(0, ncol = ncol(tot_E) + 1, nrow = nrow(tot_E)))
# En[1,] <- tot_E %>% filter(Region == "East", Scenario == "Baseline") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Baseline"])))
# En[2,] <- tot_E %>% filter(Region == "East", Scenario == "Projected") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Projected"])))
# En[3,] <- tot_E %>% filter(Region == "East", Scenario == "High") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "High"])))
# En[4,] <- tot_E %>% filter(Region == "West", Scenario == "Baseline") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Baseline"])))
# En[5,] <- tot_E %>% filter(Region == "West", Scenario == "Projected") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Projected"])))
# En[6,] <- tot_E %>% filter(Region == "West", Scenario == "High") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "High"])))
# En[7,] <- tot_E %>% filter(Region == "Southern", Scenario == "Baseline") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Baseline"])))
# En[8,] <- tot_E %>% filter(Region == "Southern", Scenario == "Projected") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Projected"])))
# En[9,] <- tot_E %>% filter(Region == "Southern", Scenario == "High") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "High"])))
# En[10,] <- tot_E %>% filter(Region == "Central", Scenario == "Baseline") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Baseline"])))
# En[11,] <- tot_E %>% filter(Region == "Central", Scenario == "Projected") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Projected"])))
# En[12,] <- tot_E %>% filter(Region == "Central", Scenario == "High") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "High"])))
# En[13,] <- tot_E %>% filter(Region == "North", Scenario == "Baseline") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Baseline"])))
# En[14,] <- tot_E %>% filter(Region == "North", Scenario == "Projected") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Projected"])))
# En[15,] <- tot_E %>% filter(Region == "North", Scenario == "High") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "High"])))
# En[16,] <- tot_E %>% filter(Region == "Africa", Scenario == "Baseline") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Baseline"])))
# En[17,] <- tot_E %>% filter(Region == "Africa", Scenario == "Projected") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "Projected"])))
# En[18,] <- tot_E %>% filter(Region == "Africa", Scenario == "High") %>% mutate( SS = with(Energy_emis_E,sum(MoE2[Scenario == "High"])))                          
# colnames(En) <- c("Scenario", "Region", "Energy", "SummedSqs")
# En$SS_sqrt <- sqrt(En$SummedSqs)
# En$upr <- En$Energy + En$SS_sqrt
# En$lwr <- En$Energy - En$SS_sqrt
# En$Energy <- En$Energy * Gg_to_Gt * Gt_Mt
# En$upr <- En$upr  * Gg_to_Gt * Gt_Mt
# En$lwr <- En$lwr  * Gg_to_Gt * Gt_Mt
# En$Scenario <- ifelse(En$Scenario == 1, "Baseline", ifelse(En$Scenario == 3, "Projected", ifelse(En$Scenario == 2, "High", NA)))
#
#convert to megatons
tot_E$Energy <- tot_E$Energy * Gg_to_Gt * Gt_Mt
#new lwr and upr bounds for tot_e
En2 <- as.data.frame(matrix(0, ncol = ncol(tot_E) + 1, nrow = nrow(tot_E)))
En2[1,] <-  tot_E %>% filter(Region == "East", Scenario == "Baseline") %>% mutate(lwr_new = with(Energy_emis_E,sum(lwr[Scenario == "Baseline"])))
En2[2,] <- tot_E %>% filter(Region == "East", Scenario == "Projected") %>% mutate( lwr_new = with(Energy_emis_E,sum(lwr[Scenario == "Projected"])))
En2[3,] <- tot_E %>% filter(Region == "East", Scenario == "High") %>% mutate(lwr_new = with(Energy_emis_E,sum(lwr[Scenario == "High"])))
En2[4,] <- tot_E %>% filter(Region == "West", Scenario == "Baseline") %>% mutate(lwr_new = with(Energy_emis_W,sum(lwr[Scenario == "Baseline"])))
En2[5,] <- tot_E %>% filter(Region == "West", Scenario == "Projected") %>% mutate(lwr_new = with(Energy_emis_W,sum(lwr[Scenario == "Projected"])))
En2[6,] <- tot_E %>% filter(Region == "West", Scenario == "High") %>% mutate(lwr_new = with(Energy_emis_W,sum(lwr[Scenario == "High"])))
En2[7,] <- tot_E %>% filter(Region == "Southern", Scenario == "Baseline") %>% mutate(lwr_new = with(Energy_emis_S,sum(lwr[Scenario == "Baseline"])))
En2[8,] <- tot_E %>% filter(Region == "Southern", Scenario == "Projected") %>% mutate(lwr_new = with(Energy_emis_S,sum(lwr[Scenario == "Projected"])))
En2[9,] <- tot_E %>% filter(Region == "Southern", Scenario == "High") %>% mutate(lwr_new = with(Energy_emis_S,sum(lwr[Scenario == "High"])))
En2[10,] <- tot_E %>% filter(Region == "Central", Scenario == "Baseline") %>% mutate(lwr_new = with(Energy_emis_C,sum(lwr[Scenario == "Baseline"])))
En2[11,] <- tot_E %>% filter(Region == "Central", Scenario == "Projected") %>% mutate(lwr_new = with(Energy_emis_C,sum(lwr[Scenario == "Projected"])))
En2[12,] <- tot_E %>% filter(Region == "Central", Scenario == "High") %>% mutate(lwr_new = with(Energy_emis_C,sum(lwr[Scenario == "High"])))
En2[13,] <- tot_E %>% filter(Region == "North", Scenario == "Baseline") %>% mutate(lwr_new = with(Energy_emis_N,sum(lwr[Scenario == "Baseline"])))
En2[14,] <- tot_E %>% filter(Region == "North", Scenario == "Projected") %>% mutate(lwr_new = with(Energy_emis_N,sum(lwr[Scenario == "Projected"])))
En2[15,] <- tot_E %>% filter(Region == "North", Scenario == "High") %>% mutate( lwr_new = with(Energy_emis_N,sum(lwr[Scenario == "High"])))
En2[16,] <- tot_E %>% filter(Region == "Africa", Scenario == "Baseline") %>% mutate(lwr_new = with(Energy_emis_Afr,sum(lwr[Scenario == "Baseline"])))
En2[17,] <- tot_E %>% filter(Region == "Africa", Scenario == "Projected") %>% mutate(lwr_new = with(Energy_emis_Afr,sum(lwr[Scenario == "Projected"])))
En2[18,] <- tot_E %>% filter(Region == "Africa", Scenario == "High") %>% mutate(lwr_new = with(Energy_emis_Afr,sum(lwr[Scenario == "High"])))
colnames(En2) <- c("Scenario", "Region", "value", "upr", "lwr","variable" , "lwr_new")
En2$Scenario <- ifelse(En2$Scenario == 1, "Baseline", ifelse(En2$Scenario == 3, "Projected", ifelse(En2$Scenario == 2, "High", NA)))

 #merge lwr and upr bounds with tot_E data

 tot_E <- merge(tot_E, En)
 tot_E$SummedSqs <- NULL
#tot_E$SS_sqrt <- NULL
tot_E$variable <- "Energy"
 colnames(tot_E) <- c("Scenario" , "Region"  ,"value" ,  "upr" , "lwr" ,  "variable")
 LUC_Afr_regions$variable <- "LUC"
 colnames(LUC_Afr_regions) <- c("Region" , "Scenario"  ,"value", "variable")
 LUC_Afr_regions$value <- (LUC_Afr_regions$value * kg_to_Gg *Gg_to_Gt)/380
 GHG <- full_join(tot_E, LUC_Afr_regions)
 GHG[GHG$upr == 0] <- NA
#
 
tot_E$Scenario <- as.character(unlist(tot_E$Scenario))
upr_new <- as.data.frame(matrix(0, nrow = nrow(tot_E), ncol = ncol(tot_E) + 1))
upr_new[1,] <- tot_E %>% filter(Region == "East", Scenario == "Baseline") %>% mutate(upr_new = with(Energy_emis_E,sum(upr[Scenario == "Baseline"])))
upr_new[2,] <- tot_E %>% filter(Region == "East", Scenario == "Projected") %>% mutate( upr_new = with(Energy_emis_E,sum(upr[Scenario == "Projected"])))
upr_new[3,] <- tot_E %>% filter(Region == "East", Scenario == "High") %>% mutate(upr_new = with(Energy_emis_E,sum(upr[Scenario == "High"])))
upr_new[4,] <- tot_E %>% filter(Region == "West", Scenario == "Baseline") %>% mutate(upr_new = with(Energy_emis_W,sum(upr[Scenario == "Baseline"])))
upr_new[5,] <- tot_E %>% filter(Region == "West", Scenario == "Projected") %>% mutate(upr_new = with(Energy_emis_W,sum(upr[Scenario == "Projected"])))
upr_new[6,] <- tot_E %>% filter(Region == "West", Scenario == "High") %>% mutate(upr_new = with(Energy_emis_W,sum(upr[Scenario == "High"])))
upr_new[7,] <- tot_E %>% filter(Region == "Southern", Scenario == "Baseline") %>% mutate(upr_new = with(Energy_emis_S,sum(upr[Scenario == "Baseline"])))
upr_new[8,] <- tot_E %>% filter(Region == "Southern", Scenario == "Projected") %>% mutate(upr_new = with(Energy_emis_S,sum(upr[Scenario == "Projected"])))
upr_new[9,] <- tot_E %>% filter(Region == "Southern", Scenario == "High") %>% mutate(upr_new = with(Energy_emis_S,sum(upr[Scenario == "High"])))
upr_new[10,] <- tot_E %>% filter(Region == "Central", Scenario == "Baseline") %>% mutate(upr_new = with(Energy_emis_C,sum(upr[Scenario == "Baseline"])))
upr_new[11,] <- tot_E %>% filter(Region == "Central", Scenario == "Projected") %>% mutate(upr_new = with(Energy_emis_C,sum(upr[Scenario == "Projected"])))
upr_new[12,] <- tot_E %>% filter(Region == "Central", Scenario == "High") %>% mutate(upr_new = with(Energy_emis_C,sum(upr[Scenario == "High"])))
upr_new[13,] <- tot_E %>% filter(Region == "North", Scenario == "Baseline") %>% mutate(upr_new = with(Energy_emis_N,sum(upr[Scenario == "Baseline"])))
upr_new[14,] <- tot_E %>% filter(Region == "North", Scenario == "Projected") %>% mutate(upr_new = with(Energy_emis_N,sum(upr[Scenario == "Projected"])))
upr_new[15,] <- tot_E %>% filter(Region == "North", Scenario == "High") %>% mutate( upr_new = with(Energy_emis_N,sum(upr[Scenario == "High"])))
upr_new[16,] <- tot_E %>% filter(Region == "Africa", Scenario == "Baseline") %>% mutate(upr_new = with(Energy_emis_Afr,sum(upr[Scenario == "Baseline"])))
upr_new[17,] <- tot_E %>% filter(Region == "Africa", Scenario == "Projected") %>% mutate(upr_new = with(Energy_emis_Afr,sum(upr[Scenario == "Projected"])))
upr_new[18,] <- tot_E %>% filter(Region == "Africa", Scenario == "High") %>% mutate(upr_new = with(Energy_emis_Afr,sum(upr[Scenario == "High"])))
colnames(upr_new) <-  c("Scenario", "Region", "value", "upr", "lwr","variable" , "upr_new")
En2 <- merge(En2, upr_new)
tot_E <- merge(tot_E, En2)  
LUC_Afr_regions$value  <- LUC_Afr_regions$value * Gt_Mt
GHG <- full_join(tot_E, LUC_Afr_regions)


#Energy_LUC_GHG <- Energy_LUC[Energy_LUC$variable == "GHG",] #exclude total GHG emissions, units are gigatons
#Energy_LUC_GHG  <- anti_join(Energy_LUC , Energy_LUC_GHG )
Energy_LUC_E <- filter(GHG, Region == "East")
Energy_LUC_W <- filter(GHG, Region == "West")
Energy_LUC_C <- filter(GHG, Region == "Central")
Energy_LUC_S <- filter(GHG, Region == "Southern")
Energy_LUC_N <- filter(GHG, Region == "North")
Energy_LUC_Afr <- filter(GHG, Region == "Africa")
Energy_LUC_Afr$variable <- str_replace(Energy_LUC_Afr$variable, "Energy", "Inputs")
Energy_LUC_E$variable <- str_replace(Energy_LUC_E$variable, "Energy", "Inputs")
Energy_LUC_W$variable <- str_replace(Energy_LUC_W$variable, "Energy", "Inputs")
Energy_LUC_C$variable <- str_replace(Energy_LUC_C$variable, "Energy", "Inputs")
Energy_LUC_S$variable <- str_replace(Energy_LUC_S$variable, "Energy", "Inputs")
Energy_LUC_N$variable <- str_replace(Energy_LUC_N$variable, "Energy", "Inputs")

#Graph Energy + LUC graphs
#East
Energy_LUC_E$Scenario <- factor(Energy_LUC_E$Scenario,levels = c("Baseline", "Projected", "High"))
Energy_LUC_E_plot <- ggplot(Energy_LUC_E , aes(fill = variable , y = value , x= Scenario)) + 
    geom_bar(position="dodge", stat="identity") + xlab("") + ylab("") + labs(fill = "Emissions Type") + scale_x_discrete(labels= x.axis) + scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) +  geom_errorbar(aes(ymin= lwr_new , ymax= upr_new), width=.2, position=position_dodge(.9)) + theme_bti()
Energy_LUC_E_plot <- Energy_LUC_E_plot  +  scale_fill_manual(values= bti_colors) 
#West
Energy_LUC_W$Scenario <- factor(Energy_LUC_W$Scenario,levels = c("Baseline", "Projected", "High"))
Energy_LUC_W_plot <- ggplot(Energy_LUC_W , aes(fill = variable , y = value , x= Scenario)) + 
    geom_bar(position="dodge", stat="identity") + xlab("") + ylab("") + labs(fill = "Emissions Type") +  geom_errorbar(aes(ymin= Energy_LUC_W$lwr_new, ymax= Energy_LUC_W$upr_new), width=.2, position=position_dodge(.9))  + scale_x_discrete(labels= x.axis)  + scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) + theme_bti() 
Energy_LUC_W_plot <- Energy_LUC_W_plot  +  scale_fill_manual(values= bti_colors) 

Energy_LUC_S$Scenario <- factor(Energy_LUC_S$Scenario,levels = c("Baseline", "Projected", "High"))
Energy_LUC_S_plot <- ggplot(Energy_LUC_S , aes(fill = variable , y = value , x= Scenario)) + 
    geom_bar(position="dodge", stat="identity") + xlab("") + ylab("") + labs(fill = "Emissions Type") +  geom_errorbar(aes(ymin= lwr_new, ymax= upr_new), width= 0.2, position=position_dodge(0.9)) + scale_x_discrete(labels= x.axis) + scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) +  theme_bti() 
Energy_LUC_S_plot <- Energy_LUC_S_plot  +  scale_fill_manual(values= bti_colors) 

Energy_LUC_N$Scenario <- factor(Energy_LUC_N$Scenario,levels = c("Baseline", "Projected", "High"))
Energy_LUC_N_plot <- ggplot(Energy_LUC_N, aes(fill = variable , y = value , x= Scenario)) + 
    geom_bar(position="dodge", stat="identity") + xlab("") + ylab("") + labs(fill = "Emissions Type") + geom_errorbar(aes(ymin= Energy_LUC_N$lwr_new, ymax= Energy_LUC_N$upr_new), width =0.2, position = position_dodge(0.9))  + scale_x_discrete(labels= x.axis) + scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) +  theme_bti()  
Energy_LUC_N_plot <- Energy_LUC_N_plot  +  scale_fill_manual(values= bti_colors) 

Energy_LUC_C$Scenario <- factor(Energy_LUC_C$Scenario,levels = c("Baseline", "Projected", "High"))
Energy_LUC_C_plot <- ggplot(Energy_LUC_C , aes(fill = variable , y = value , x= Scenario)) + 
    geom_bar(position="dodge", stat="identity") + xlab("") + ylab("") + labs(fill = "Emissions Type") + geom_errorbar(aes(ymin= lwr_new, ymax= upr_new), width = 0.2, position = position_dodge(0.9))  + scale_x_discrete(labels= x.axis) + scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) +  theme_bti() 
Energy_LUC_C_plot <- Energy_LUC_C_plot  +  scale_fill_manual(values= bti_colors) 

#Africa
Energy_LUC_Afr$lwr_new <- Energy_LUC_Afr$lwr_new  * Gt_Mt
Energy_LUC_Afr$upr_new <- Energy_LUC_Afr$upr_new  * Gt_Mt
Energy_LUC_Afr$Scenario <- factor(Energy_LUC_Afr$Scenario,levels = c("Baseline", "Projected", "High"))
Energy_LUC_Afr_plot <- ggplot(Energy_LUC_Afr , aes(fill = variable , y = value , x= Scenario)) +
    geom_bar(position="dodge", stat="identity") + xlab("") + ylab("") + labs(fill = "Emissions Type") + geom_errorbar(aes(ymin= lwr_new, ymax= upr_new), width = 0.2, position = position_dodge(0.9))   + scale_x_discrete(labels= x.axis) +scale_y_continuous(expand = expand_scale(mult = c(0.0, 0.1))) +  theme_bti() 
Energy_LUC_Afr_plot <- Energy_LUC_Afr_plot  +  scale_fill_manual(values= bti_colors) 

energy_LUC_grafs2 <- ggarrange(Energy_LUC_N_plot, Energy_LUC_S_plot, Energy_LUC_W_plot, Energy_LUC_E_plot, Energy_LUC_C_plot,Energy_LUC_Afr_plot, labels = c("North", "Southern","West","East", "Central", "Africa"), hjust = 0,vjust = 0.4, font.label = list(size = 10, face = "plain", color = "black", family = NULL), common.legend = TRUE, legend = "bottom")


# Annotate the figure by adding a common labels
energy_LUC_grafs2 <- annotate_figure(energy_LUC_grafs2,
                top = text_grob("", color = "black" , size = 10),
                left = text_grob("GHG Emissions (Mt CO2eq)", color = "black", rot = 90))
                
                #fig.lab = "Figure 1", fig.lab.face = "bold")
ggsave(filename = "~/Google Drive/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/energy_LUC_grafs.png", plot = energy_LUC_grafs2, width = , height = )


write.csv(Energy_emis_C, "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/Energy_emis_C.csv")
write.csv(Energy_emis_E, "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/Energy_emis_E.csv")
write.csv(Energy_emis_S, "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/Energy_emis_S.csv")
write.csv(Energy_emis_W, "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/Energy_emis_W.csv")
write.csv(Energy_emis_N, "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/Energy_emis_N.csv")
write.csv(Energy_emis_Afr, "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/results/Energy-Ag_tbls/Energy_emis_Afr.csv")
```


```{r LUC emis graph, all emis sources graph }

#plot results  
LUC_emis <- GHG[, c(1:3)]
x.axis <- c("Baseline", "Projected", "High")

LUC_emis_Afr <- LUC_emis[LUC_emis$Region == "Africa",] #have separate charts for SSA data to compare to region breakdown
LUC_emis <- anti_join(LUC_emis, LUC_emis_Afr)
LUC_emis$Scenario <- str_replace(LUC_emis$Scenario, "High_alt","High")
LUC_emis$Scenario <- factor(LUC_emis$Scenario,levels = c("Baseline", "Projected", "High"))

LUC_regions <- ggplot(LUC_emis , aes(fill = Region , y = LUC , x = Scenario)) + 
    geom_bar(position="dodge", stat="identity" ) + ggtitle(expression(paste("LUC emissions by scenario and region"))) + xlab("Scenario") + ylab("LUC Emissions (Gt CO2 eq)") + labs(fill = "Region")  +  scale_x_discrete(labels= x.axis) + theme_bti()

LUC_regions  <- LUC_regions  +  scale_fill_manual(values= bti_colors)
ggsave(filename = "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/results/LUC_regions_grouped", plot = LUC_regions , width = , height = )

#LUC stacked chart 
LUC_stacked <- ggplot(LUC_Afr_regions , aes(fill = Region , y = `LUC emissions(Gt)`, x = Scenario)) + 
    geom_bar(position="fill", stat="identity" ) + ggtitle(expression(paste("% LUC emissions by region for each scenario"))) + xlab("Scenario") + ylab("% LUC emissions") + labs(fill = "Region")  +  scale_x_discrete(labels= x.axis) + theme(axis.title.x = element_text(color="black",size=12),axis.title.y = element_text(color="black", size=12) ,panel.background = element_rect(fill = NA),
       panel.grid.major.y = element_line(colour="grey68",linetype="dotted"),
       panel.grid.major.x = element_line(colour="grey68",linetype="dotted"),axis.ticks.y = element_blank(),axis.ticks.x=element_blank(),
       plot.title = element_text(size=13, face="bold"))

LUC_stacked <- LUC_stacked +  scale_fill_manual(values=wes_palette(n=5, name="Darjeeling1"))
ggsave(filename = "~/Google Drive File Stream/My Drive/Food & Farming/Energy in ag/results/Graphs/New Graphs/LUC_stacked_reg", plot = LUC_stacked , width = , height = )


#LUC_SSA chart
LUC_SSA$Scenario <- factor(LUC_SSA$Scenario,levels = c("Baseline", "Projected", "High_alt"))
LUC_SSA <- as.data.frame(na.omit(LUC_Afr_regions))
LUC_SSA <- ggplot(LUC_Afr_regions , aes(y = LUC, x = Scenario)) + 
    geom_bar(position="dodge", stat="identity", fill = "#0DC3A8") + ggtitle(expression(paste("LUC emissions by scenario in Sub-Saharan Africa"))) + xlab("Scenario") + ylab("LUC Emissions (Gt CO2 eq)")  +  scale_x_discrete(labels= x.axis) + theme(axis.title.x = element_text(color="black",size=12),axis.title.y = element_text(color="black", size=12) ,panel.background = element_rect(fill = NA),
       panel.grid.major.y = element_line(colour="grey68",linetype="dotted"),
       panel.grid.major.x = element_line(colour="grey68",linetype="dotted"),axis.ticks.y = element_blank(),axis.ticks.x=element_blank(),
       plot.title = element_text(size=13, face="bold"))

ggsave(filename = "~/Desktop/Grafs_energyag/LUC_SSA.png", plot = LUC_SSA , width = , height = )





#Stacked bar chart

bp <- ggplot(all_emis_melted, aes(fill= variable, y= LUC, x=Scenario)) + 
    geom_bar(position="stack", stat="identity") + ggtitle(expression(paste("Emissions by Scenario"))) + xlab("Scenario") + ylab("GHG Emissions (CO2eq)") + labs(fill = "Categories") + theme(axis.title.x = element_text(color="black",size=12),axis.title.y = element_text(color="black", size=12) ,panel.background = element_rect(fill = NA),
       panel.grid.major.y = element_line(colour="grey68",linetype="dotted"),
       panel.grid.major.x = element_line(colour="grey68",linetype="dotted"), axis.ticks.y = element_blank(),axis.ticks.x=element_blank(),
       plot.title = element_text(size=13, face="bold"))

positions <- c("Baseline Yield", "Projected Yield", "High Yield")
bp + scale_x_discrete(limits = positions) 
bp

colnames(all_emis) <- c("LUC", "Total Energy + LUC emissions", "Synthetic N emissions", "On Farm Fuel Emissions", "Manufacturing Pesticides Emissions", "Manufacturing Nitrogen Emissions", "Manufacturing Nitrogen Emissions 2", "Energy Embodied in Machinery Emissions", "Total Energy Emissions", "Scenario")
rownames(all_emis) <- c("current", "projected", "high")
write_csv(all_emis, path = "~/Google Drive/Energy and GHG Analysis (2019)/energy_ag_analysis/Results/LUC_Energy_Emissions.csv")


```


```{r OLS Estimators table and Predictions Estimator table}
m.ols_coef <- rbind(m.ols$coefficients[1],m.ols$coefficients[2])
p.ols_coef <- rbind(p.ols$coefficients[1],p.ols$coefficients[2])
fert_use.coef  <- rbind(fert_use.ols$coefficients[1],fert_use.ols$coefficients[2])
syn_n.coef <- rbind(syn_n.ols$coefficients[1],syn_n.ols$coefficients[2])
fuel.coef <- rbind(fuel.ols$coefficients[1], fuel.ols$coefficients[2])
energy_coefs <- cbind(m.ols_coef, p.ols_coef, syn_n.coef, fert_use.coef, fuel.coef)
colnames(energy_coefs) <- c("machinery energy emissions", "manufacturing pesticides emissions", "synthetic N fertilizer emissions", "manufacturing fertilizers emissions", "on-farm fuel energy emissions")
energy_coefs[2,1] <- exp(energy_coefs[2,1])
energy_coefs[2,2] <- exp(energy_coefs[2,2])
energy_coefs[2,3] <- exp(energy_coefs[2,3])
energy_coefs[2,4] <- exp(energy_coefs[2,4])
energy_coefs[2,5] <- exp(energy_coefs[2,5])

rownames(energy_coefs) <- c("Intercept", "Yield")
energy_coefs <- as.data.frame(energy_coefs)
write_csv(energy_coefs, "~/Google Drive/Energy and GHG Analysis (2019)/energy_ag_analysis/Results/energy_coefs.csv")

write_csv(predict_tbl, path = "~/Google Drive/Energy and GHG Analysis (2019)/energy_ag_analysis/Results/predict_tbl.csv")

#Error Bars
fuel.ols <- as.data.frame(fuel.ols$coefficients)
write.csv(fuel.ols, "~/Desktop/Energy-Ag_tbls/Fuel_coeffs.csv")
p.coeffs <- as.data.frame(p.ols$coefficients)
p.coeffs$coeffs <- rownames(p.coeffs)
rownames(p.coeffs) <- NULL
write.csv(p.coeffs, "~/Desktop/Energy-Ag_tbls/p_coeffs.csv")
m.coeffs <- as.data.frame(m.ols$coefficients)
m.coeffs$coeffs <- rownames(m.coeffs)
rownames(p.coeffs) <- NULL
write.csv(m.coeffs, "~/Desktop/Energy-Ag_tbls/m_coeffs.csv")

fert_use.coeffs <- as.data.frame(fert_use.ols$coefficients)
fert_use.coeffs$coeffs <- rownames(fert_use.coeffs)
rownames(fert_use.coeffs) <- NULL
write.csv(fert_use.coeffs, "~/Desktop/Energy-Ag_tbls/fert_use_coeffs.csv")

syn_n.coeffs <- as.data.frame(syn_n.ols$coefficients)
syn_n.coeffs$coeffs <- rownames(syn_n.coeffs)
rownames(syn_n.coeffs) <- NULL
write.csv(syn_n.coeffs, "~/Desktop/Energy-Ag_tbls/syn_n_coeffs.csv")



```
```{r Additional Data Viz}

```

```{r Calculations comparing scenarios}
pct_c_p <- (Energy_emissions$total[2] -  Energy_emissions$total[1])/Energy_emissions$total[1]
pct_c_h <- (Energy_emissions$total[3] -  Energy_emissions$total[1])/Energy_emissions$total[1]
pct_yld_p <- (unlist(Yield_scenarios$projected[1]) -  unlist(Yield_scenarios$current[1])/unlist(Yield_scenarios$current[1])) 
(all_emis$`Total Energy + LUC emissions`[2] - all_emis$LUC[2])/all_emis$LUC[2]
```